import { useEffect, useMemo, useState } from "react";
import { Building2, CheckCircle2, Clock3, ShieldCheck, XCircle } from "lucide-react";
import { _get, _put } from "../../utils/ApiService";
import { showError, showSuccess } from "../../utils/toaster";
import useAuthStore from "../../stores/authStore";

const statuses = ["PENDING", "ACTIVE", "SUSPENDED", "REJECTED"];
const tone = { PENDING:"bg-amber-100 text-amber-800", ACTIVE:"bg-emerald-100 text-emerald-800", SUSPENDED:"bg-orange-100 text-orange-800", REJECTED:"bg-red-100 text-red-800" };

export default function PlatformAdmin() {
  const user = useAuthStore((state) => state.userData?.user);
  const [filter,setFilter]=useState("PENDING"), [data,setData]=useState({organisations:[],counts:{}}), [loading,setLoading]=useState(true), [busy,setBusy]=useState(""), [notes,setNotes]=useState({});
  const load=async()=>{setLoading(true);try{const response=await _get("/api/platform/organisations",{params:filter?{status:filter}:{}});setData(response.data.results.data);}catch(error){showError(error.response?.data?.message||"Unable to load business applications");}finally{setLoading(false);}};
  useEffect(()=>{load();},[filter]);
  const review=async(id,status)=>{setBusy(id+status);try{await _put(`/api/platform/organisations/${id}/status`,{status,notes:notes[id]||""});showSuccess(`Organisation ${status.toLowerCase()}`);await load();}catch(error){showError(error.response?.data?.message||"Unable to update organisation");}finally{setBusy("");}};
  const counts=useMemo(()=>statuses.map(status=>({status,count:data.counts?.[status]||0})),[data.counts]);
  if(!user?.isPlatformAdmin)return <div className="p-10"><h1 className="text-2xl font-semibold">Platform administrator access required</h1></div>;
  return <main className="min-h-[calc(100vh-64px)] bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-7xl">
    <header className="mb-7 flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-customBlue"><ShieldCheck/><span className="text-sm font-semibold uppercase tracking-wide">Caremonitor platform</span></div><h1 className="mt-1 text-3xl font-bold text-slate-900">Business approvals</h1><p className="mt-1 text-slate-500">Review organisations before owners can access care data and operational tools.</p></div><button onClick={load} className="rounded-lg border bg-white px-4 py-2 font-medium shadow-sm">Refresh</button></header>
    <section className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{counts.map(({status,count})=><button key={status} onClick={()=>setFilter(status)} className={`rounded-xl border bg-white p-4 text-left shadow-sm ${filter===status?"ring-2 ring-customBlue":""}`}><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${tone[status]}`}>{status}</span><strong className="mt-3 block text-3xl text-slate-900">{count}</strong></button>)}</section>
    {loading?<div className="rounded-xl border bg-white p-10 text-center text-slate-500">Loading applications…</div>:!data.organisations.length?<div className="rounded-xl border bg-white p-10 text-center"><CheckCircle2 className="mx-auto mb-3 text-emerald-600"/><h2 className="font-semibold">No {filter.toLowerCase()} organisations</h2></div>:<div className="space-y-4">{data.organisations.map(org=><article key={org.id} className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-4"><div className="flex gap-3"><div className="rounded-xl bg-cyan-50 p-3 text-customBlue"><Building2/></div><div><h2 className="text-xl font-semibold text-slate-900">{org.name}</h2><p className="text-sm text-slate-500">{org.business_type?.replaceAll("_"," ")} · {org.registration_number||"No registration number supplied"}</p><p className="mt-1 text-sm text-slate-600">Owner: {org.first_name} {org.last_name} · {org.email}</p></div></div><span className={`h-fit rounded-full px-3 py-1 text-xs font-bold ${tone[org.status]}`}>{org.status}</span></div><div className="mt-4 grid gap-3 text-sm md:grid-cols-3"><p><b>Contact</b><br/>{org.phone}</p><p><b>Location</b><br/>{[org.city,org.state,org.country,org.postcode].filter(Boolean).join(", ")}</p><p><b>Submitted</b><br/>{new Date(org.submitted_at||org.created_at).toLocaleString()}</p></div><label className="mt-4 block text-sm font-medium">Review notes<textarea value={notes[org.id]||""} onChange={e=>setNotes(old=>({...old,[org.id]:e.target.value}))} maxLength={2000} rows={2} className="mt-1 w-full rounded-lg border px-3 py-2" placeholder="Optional notes shared with the business owner"/></label><div className="mt-4 flex flex-wrap gap-2">{org.status!=="ACTIVE"&&<button disabled={!!busy} onClick={()=>review(org.id,"ACTIVE")} className="flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 font-semibold text-white disabled:opacity-50"><CheckCircle2 size={17}/>Approve and activate</button>}{org.status!=="SUSPENDED"&&<button disabled={!!busy} onClick={()=>review(org.id,"SUSPENDED")} className="flex items-center gap-2 rounded-lg border border-orange-300 px-4 py-2 font-semibold text-orange-700 disabled:opacity-50"><Clock3 size={17}/>Suspend</button>}{org.status!=="REJECTED"&&<button disabled={!!busy} onClick={()=>review(org.id,"REJECTED")} className="flex items-center gap-2 rounded-lg border border-red-300 px-4 py-2 font-semibold text-red-700 disabled:opacity-50"><XCircle size={17}/>Reject</button>}</div></article>)}</div>}
  </div></main>;
}
