import {useCallback,useEffect,useState} from "react";
import {useSearchParams} from "react-router-dom";
import {_get,_post,_postForm} from "../../utils/ApiService";
import {Page,ErrorBox,buttonClass,inputClass} from "../../components/Operations/common";
const val=r=>r.data.results.data,blankCase={clientId:"",kind:"INCIDENT",severity:"MEDIUM",title:"",description:"",ownerId:"",dueAt:""},blankPolicy={title:"",version:"1.0",status:"DRAFT",effectiveAt:"",reviewAt:"",documentUrl:""},blankCredential={staffId:"",kind:"",reference:"",issuedAt:"",expiresAt:"",evidenceUrl:""};
const paths=["assistance-prompts","overview","cases","policies","credentials","ai-reviews","metrics","settings","ai-models","report-schedules","release-signoffs"];
const governanceTabs=["overview","cases","policies","credentials","assistance","analytics","release"];
export default function GovernanceIndex(){
 const [params,setParams]=useSearchParams(),requestedTab=params.get("tab"),[tab,setTab]=useState(governanceTabs.includes(requestedTab)?requestedTab:"overview"),[data,setData]=useState({}),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[caseForm,setCase]=useState(blankCase),[policy,setPolicy]=useState(blankPolicy),[credential,setCredential]=useState(blankCredential),[ai,setAi]=useState({clientId:"",kind:"RISK_SIGNAL"}),[evidence,setEvidence]=useState({entityType:"CASE",entityId:"",file:null}),[schedule,setSchedule]=useState({name:"Monthly governance pack",reportKind:"GOVERNANCE",cadence:"MONTHLY",recipientEmails:""}),[signoff,setSignoff]=useState({persona:"CARE_MANAGER",scenario:"",result:"PASS",evidence:""});
 useEffect(()=>{const next=params.get("tab")||"overview";if(governanceTabs.includes(next))setTab(next)},[params]);
 const load=useCallback(async()=>{try{const rs=await Promise.all([...paths.map(p=>_get(`/api/governance/${p}`)),_get("/api/privacy/subjects")]),next={};paths.forEach((p,i)=>next[p]=val(rs[i]));next.subjects=val(rs.at(-1));setData(next);setError("")}catch(e){setError(e.response?.data?.message||"Unable to load governance workspace")}},[]);
 useEffect(()=>{load()},[load]);
 const run=async(fn,msg)=>{setBusy(true);setError("");setNotice("");try{await fn();setNotice(msg);await load()}catch(e){setError(e.response?.data?.message||"The governance action could not be completed")}finally{setBusy(false)}};
 const clients=(data.subjects||[]).filter(x=>x.role==="USER"),staff=(data.subjects||[]).filter(x=>x.role!=="USER"),tabs=governanceTabs;
 const download=async()=>{const pack=val(await _get("/api/governance/evidence-pack")),url=URL.createObjectURL(new Blob([JSON.stringify(pack,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download=`caremonitor-evidence-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)};
 return <Page title="Governance and quality" description="Quality, evidence, workforce assurance, family engagement, responsible assistance and release controls.">
  <div className="flex flex-wrap gap-2">{tabs.map(x=><button key={x} onClick={()=>{setTab(x);setParams(x==="overview"?{}:{tab:x},{replace:true})}} className={tab===x?buttonClass:"rounded-lg border px-4 py-2 text-sm font-semibold"}>{x==="assistance"?"AI Assistance":x[0].toUpperCase()+x.slice(1)}</button>)}</div><ErrorBox error={error}/>{notice&&<p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}
  {tab==="overview"&&<Overview data={data} busy={busy} run={run} download={download}/>}
  {tab==="cases"&&<><Form title="Record quality case" busy={busy} submit={e=>{e.preventDefault();run(()=>_post("/api/governance/cases",{...caseForm,clientId:caseForm.clientId||null,ownerId:caseForm.ownerId||null,dueAt:caseForm.dueAt?new Date(caseForm.dueAt).toISOString():null}),"Quality case recorded").then(()=>setCase(blankCase))}}><Select label="Client (optional)" value={caseForm.clientId} set={v=>setCase({...caseForm,clientId:v})} options={clients}/><Select label="Owner (optional)" value={caseForm.ownerId} set={v=>setCase({...caseForm,ownerId:v})} options={staff}/><Select label="Type" value={caseForm.kind} set={v=>setCase({...caseForm,kind:v})} values={["INCIDENT","SAFEGUARDING","COMPLAINT","AUDIT_FINDING"]}/><Select label="Severity" value={caseForm.severity} set={v=>setCase({...caseForm,severity:v})} values={["LOW","MEDIUM","HIGH","CRITICAL"]}/><Input label="Title" value={caseForm.title} set={v=>setCase({...caseForm,title:v})} required/><Input label="Due" type="datetime-local" value={caseForm.dueAt} set={v=>setCase({...caseForm,dueAt:v})}/><Text label="Description" value={caseForm.description} set={v=>setCase({...caseForm,description:v})}/></Form><Cards title="Quality cases" rows={data.cases||[]} render={x=><><b>{x.title}</b><p>{x.kind.replaceAll("_"," ")} · {x.severity} · {x.status}</p><small>{x.ownerName||"Unassigned"} · revision {x.revision}</small><div className="mt-2 flex gap-2"><button onClick={()=>run(()=>_post(`/api/governance/cases/${x.id}/status`,{status:"INVESTIGATING",reason:"Investigation started from governance workspace",revision:x.revision}),"Investigation recorded")}>Investigate</button><button onClick={()=>run(()=>_post(`/api/governance/cases/${x.id}/escalate`,{level:x.severity==="CRITICAL"?"DIRECTOR":"MANAGER",reason:"Escalated for timely management oversight and recorded review"}),"Escalation recorded")}>Escalate</button></div></>}/></>}
  {tab==="policies"&&<><Form title="Add policy" busy={busy} submit={e=>{e.preventDefault();run(()=>_post("/api/governance/policies",{...policy,effectiveAt:policy.effectiveAt||null,reviewAt:policy.reviewAt||null,documentUrl:policy.documentUrl||null}),"Policy recorded").then(()=>setPolicy(blankPolicy))}}><Input label="Title" value={policy.title} set={v=>setPolicy({...policy,title:v})} required/><Input label="Version" value={policy.version} set={v=>setPolicy({...policy,version:v})} required/><Select label="Status" value={policy.status} set={v=>setPolicy({...policy,status:v})} values={["DRAFT","ACTIVE","RETIRED"]}/><Input label="Effective date" type="date" value={policy.effectiveAt} set={v=>setPolicy({...policy,effectiveAt:v})}/><Input label="Review date" type="date" value={policy.reviewAt} set={v=>setPolicy({...policy,reviewAt:v})}/><Input label="Document URL" type="url" value={policy.documentUrl} set={v=>setPolicy({...policy,documentUrl:v})}/></Form><Evidence form={evidence} set={setEvidence} busy={busy} run={run}/><Cards title="Policies" rows={data.policies||[]} render={x=><><b>{x.title} · v{x.version}</b><p>{x.status} · review {x.review_at||"not set"}</p><small>{x.acknowledgements} acknowledgements</small></>}/></>}
  {tab==="credentials"&&<><Form title="Record staff credential" busy={busy} submit={e=>{e.preventDefault();run(()=>_post("/api/governance/credentials",{...credential,issuedAt:credential.issuedAt||null,expiresAt:credential.expiresAt||null,evidenceUrl:credential.evidenceUrl||null}),"Credential recorded").then(()=>setCredential(blankCredential))}}><Select label="Staff" value={credential.staffId} set={v=>setCredential({...credential,staffId:v})} options={staff} required/><Input label="Credential" value={credential.kind} set={v=>setCredential({...credential,kind:v})} required/><Input label="Reference" value={credential.reference} set={v=>setCredential({...credential,reference:v})}/><Input label="Issued" type="date" value={credential.issuedAt} set={v=>setCredential({...credential,issuedAt:v})}/><Input label="Expires" type="date" value={credential.expiresAt} set={v=>setCredential({...credential,expiresAt:v})}/></Form><Evidence form={evidence} set={setEvidence} busy={busy} run={run}/><Cards title="Credentials" rows={data.credentials||[]} render={x=><><b>{x.staffName}</b><p>{x.kind} · {x.displayStatus}</p><small>Expires {x.expires_at||"not set"}</small></>}/></>}
  {tab==="assistance"&&<><p className="text-sm text-slate-600">Local rules and source extracts support review. No external AI model is connected. Suggestions do not change care records.</p><Cards title="Missing information — first 500 client profiles" rows={(data["assistance-prompts"]?.prompts||[]).map(x=>({...x,id:`${x.clientId}-${x.field}`}))} render={x=><><b>{x.clientName}</b><p>{x.message}</p><a className="underline" href={`/admin/clients/${x.clientId}`}>Review client profile</a></>}/><Form title="Generate human-review suggestion" busy={busy} submit={e=>{e.preventDefault();run(()=>_post("/api/governance/ai-reviews/generate",ai),"Suggestion queued for review")}}><Select label="Client" value={ai.clientId} set={v=>setAi({...ai,clientId:v})} options={clients} required/><Select label="Type" value={ai.kind} set={v=>setAi({...ai,kind:v})} values={["RISK_SIGNAL","NOTE_SUMMARY"]}/></Form><Cards title="Review queue" rows={data["ai-reviews"]||[]} render={x=><><b>{x.clientName} · {x.kind.replaceAll("_"," ")}</b><p className="whitespace-pre-wrap">{x.suggestion}</p><details><summary>Source evidence</summary>{(Array.isArray(x.evidence)?x.evidence:[]).map((e,i)=><p key={e.entryId} className="whitespace-pre-wrap">[{i+1}] {e.createdAt} · {e.title} · Record {e.entryId}<br/>{e.excerpt||""}</p>)}</details><small>{x.status} · evidence retained</small>{x.status==="PENDING"&&<div className="mt-2 flex gap-2"><button onClick={()=>run(()=>_post(`/api/governance/ai-reviews/${x.id}/decision`,{decision:"APPROVED",reason:"Qualified reviewer inspected the cited records and accepts this suggestion"}),"Approval recorded")}>Approve</button><button onClick={()=>run(()=>_post(`/api/governance/ai-reviews/${x.id}/decision`,{decision:"REJECTED",reason:"Qualified reviewer found the suggestion unsupported by cited records"}),"Rejection recorded")}>Reject</button></div>}</>}/><Cards title="Model register" rows={data["ai-models"]||[]} render={x=><><b>{x.model_key} · {x.version}</b><p>{x.status} · {x.risk_level} risk</p><small>{x.passedEvaluations}/{x.evaluations} passing evaluations</small></>}/></>}
  {tab==="analytics"&&<><Form title="Schedule governed report" busy={busy} submit={e=>{e.preventDefault();run(()=>_post("/api/governance/report-schedules",{...schedule,recipientEmails:schedule.recipientEmails.split(",").map(x=>x.trim()).filter(Boolean)}),"Report schedule saved")}}><Input label="Name" value={schedule.name} set={v=>setSchedule({...schedule,name:v})}/><Select label="Report" value={schedule.reportKind} set={v=>setSchedule({...schedule,reportKind:v})} values={["GOVERNANCE","OPERATIONS","FINANCE_RECONCILIATION"]}/><Select label="Cadence" value={schedule.cadence} set={v=>setSchedule({...schedule,cadence:v})} values={["WEEKLY","MONTHLY","QUARTERLY"]}/><Input label="Recipient emails, comma separated" value={schedule.recipientEmails} set={v=>setSchedule({...schedule,recipientEmails:v})} required/></Form><Cards title="Metric dictionary" rows={data.metrics||[]} render={x=><><b>{x.label}</b><p>{x.definition}</p><small>Owner: {x.owner}</small></>}/><Cards title="Report schedules" rows={data["report-schedules"]||[]} render={x=><><b>{x.name}</b><p>{x.reportKind} · {x.cadence}</p><small>Next {new Date(x.nextRunAt).toLocaleString()}</small></>}/></>}
  {tab==="release"&&<><Form title="Record acceptance sign-off" busy={busy} submit={e=>{e.preventDefault();run(()=>_post("/api/governance/release-signoffs",signoff),"Acceptance sign-off recorded")}}><Select label="Persona" value={signoff.persona} set={v=>setSignoff({...signoff,persona:v})} values={["CARE_MANAGER","CAREGIVER","CLIENT","FAMILY"]}/><Select label="Result" value={signoff.result} set={v=>setSignoff({...signoff,result:v})} values={["PASS","FAIL","BLOCKED"]}/><Text label="Scenario tested" value={signoff.scenario} set={v=>setSignoff({...signoff,scenario:v})}/><Text label="Evidence and observations" value={signoff.evidence} set={v=>setSignoff({...signoff,evidence:v})}/></Form><Cards title="Release sign-offs" rows={data["release-signoffs"]||[]} render={x=><><b>{x.persona.replaceAll("_"," ")} · {x.result}</b><p>{x.scenario}</p><small>{x.signedBy} · {new Date(x.createdAt).toLocaleString()}</small></>}/></>}
 </Page>
}
function Overview({data,busy,run,download}){const o=data.overview,cs=o?[["Open cases",o.quality.open,`${o.quality.overdue} overdue`],["Active policies",o.policies.active,`${o.policies.due} reviews due`],["Credential alerts",+o.credentials.expired + +o.credentials.expiring,`${o.credentials.expired} expired`],["AI reviews",o.ai.pending,"human decision required"]]:[];return <><div className="flex flex-wrap gap-3"><button className={buttonClass} disabled={busy} onClick={()=>run(()=>_post("/api/governance/data-quality/run"),"Checks complete")}>Run data-quality checks</button><button className={buttonClass} disabled={busy} onClick={()=>run(()=>_post("/api/governance/reminders/run"),"Reminders evaluated")}>Run reminders</button><button className={buttonClass} onClick={()=>download().catch(()=>{})}>Download evidence pack</button></div><div className="grid gap-3 md:grid-cols-4">{cs.map(([k,v,h])=><div className="rounded-xl border bg-white p-4" key={k}><p className="text-xs text-gray-500">{k}</p><p className="text-2xl font-semibold">{v}</p><small>{h}</small></div>)}</div>{o?.lastDataQualityRun&&<div className="rounded-xl border bg-white p-5"><b>Latest checks: {o.lastDataQualityRun.status}</b>{o.lastDataQualityRun.findings.map(x=><p className="text-sm" key={x.key}>{x.key.replaceAll("_"," ")}: {x.count} · {x.status}</p>)}</div>}</>}
function Form({title,submit,busy,children}){return <form onSubmit={submit} className="grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-2"><h2 className="md:col-span-2 text-lg font-semibold">{title}</h2>{children}<button className={`${buttonClass} md:col-span-2`} disabled={busy}>Save</button></form>}
function Input({label,value,set,type="text",required=false}){return <label className="space-y-1 text-sm">{label}<input className={inputClass} type={type} value={value} required={required} onChange={e=>set(e.target.value)}/></label>}
function Text({label,value,set}){return <label className="space-y-1 text-sm md:col-span-2">{label}<textarea className={inputClass} rows={3} required value={value} onChange={e=>set(e.target.value)}/></label>}
function Select({label,value,set,values,options,required=false}){return <label className="space-y-1 text-sm">{label}<select className={inputClass} value={value} required={required} onChange={e=>set(e.target.value)}><option value="">Select…</option>{values?.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}{options?.map(x=><option key={x.id} value={x.id}>{x.name} · {x.role}</option>)}</select></label>}
function Cards({title,rows,render}){return <section className="rounded-xl border bg-white p-5"><h2 className="mb-3 text-lg font-semibold">{title}</h2><div className="grid gap-3 lg:grid-cols-2">{rows.map(x=><article className="rounded-lg border p-4 text-sm" key={x.id||x.metricKey}>{render(x)}</article>)}</div>{!rows.length&&<p className="text-sm text-gray-500">No records yet.</p>}</section>}
function Evidence({form,set,busy,run}){return <form className="grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-3" onSubmit={e=>{e.preventDefault();const b=new FormData();b.append("entityType",form.entityType);b.append("entityId",form.entityId);b.append("file",form.file);run(()=>_postForm("/api/governance/evidence/upload",b),"Evidence uploaded")}}><h2 className="md:col-span-3 font-semibold">Upload supporting evidence</h2><Select label="Record type" value={form.entityType} set={v=>set({...form,entityType:v})} values={["CASE","ACTION","POLICY","CREDENTIAL"]}/><Input label="Record ID" value={form.entityId} set={v=>set({...form,entityId:v})} required/><label className="space-y-1 text-sm">File<input className={inputClass} required type="file" onChange={e=>set({...form,file:e.target.files[0]})}/></label><button className={`${buttonClass} md:col-span-3`} disabled={busy||!form.file}>Upload evidence</button></form>}
