export const clientsRelationshipOptions = [
    { label: "Spouse/Partner", value: "SPOUSE_PARTNER" },
    { label: "Son/Daughter", value: "SON_DAUGHTER" },
    { label: "Parent", value: "PARENT" },
    { label: "Sibling", value: "SIBLING" },
    { label: "Other relative", value: "OTHER_RELATIVE" },
    { label: "Friend", value: "FRIEND" },
    { label: "Neighbor", value: "NEIGHBOR" },
    { label: "Other", value: "OTHER" },
];

export const clientsContactTypeOptions = [
    { label: "Next of Kin", value: "NEXT_OF_KIN" },
    { label: "Emergency Contact", value: "EMERGENCY_CONTACT" },
    { label: "Both", value: "BOTH" },
];

export const clientsYesNoOptions = [
    { label: "Yes", value: "YES" },
    { label: "No", value: "NO" },
    { label: "Not known", value: "DONT_KNOW" },
];

export const clientsRegulatedCareOptions = [
    { label: "Yes", value: true },
    { label: "No", value: false },
];

export const clientskeysContactOptions = [
    { label: "Yes", value: true },
    { label: "No", value: false },
];

export const clientsEthnicityOptions = [
    { label: "Select option", value: "" },
    { label: "African", value: "African" },
    { label: "Asian", value: "Asian" },
    { label: "Bangladeshi", value: "Bangladeshi" },
    { label: "Black African", value: "Black African" },
    { label: "Black Caribbean", value: "Black Caribbean" },
    { label: "Black Other", value: "Black Other" },
    { label: "Caribbean", value: "Caribbean" },
    { label: "Chinese", value: "Chinese" },
    { label: "Indian", value: "Indian" },
    { label: "Mixed Asian and White", value: "Mixed Asian and White" },
    { label: "Mixed Black African and White", value: "Mixed Black African and White" },
    { label: "Mixed Black Caribbean and White", value: "Mixed Black Caribbean and White" },
    { label: "Mixed Other", value: "Mixed Other" },
    { label: "Other Asian background", value: "Other Asian background" },
    { label: "Other Black background", value: "Other Black background" },
    { label: "Other Ethnic background", value: "Other Ethnic background" },
    { label: "Other Mixed background", value: "Other Mixed background" },
    { label: "Other White background", value: "Other White background" },
    { label: "Pakistani", value: "Pakistani" },
    { label: "White British", value: "White British" },
    { label: "White Irish", value: "White Irish" },
    { label: "White Other", value: "White Other" },
    { label: "Not stated", value: "Not stated" },
];

export const clientsReligionOptions = [
    { label: "Select option", value: "" },
    { label: "Advaita Vedanta", value: "Advaita Vedanta" },
    { label: "Advent Christian Church", value: "Advent Christian Church" },
    { label: "African religion", value: "African religion" },
    { label: "Agnostic Christian", value: "Agnostic Christian" },
    { label: "Agnostic movement", value: "Agnostic movement" },
    { label: "Ahmadiyya Islam", value: "Ahmadiyya Islam" },
    { label: "Amish religion", value: "Amish religion" },
    { label: "Anabaptism", value: "Anabaptism" },
    { label: "Anglican Church", value: "Anglican Church" },
    { label: "Anthroposophy", value: "Anthroposophy" },
    { label: "Apostolic Church", value: "Apostolic Church" },
    { label: "Apostolic Pentecostal religion", value: "Apostolic Pentecostal religion" },
    { label: "Arcane school religion", value: "Arcane school religion" },
    { label: "Armenian Church", value: "Armenian Church" },
    { label: "Arminianism", value: "Arminianism" },
    { label: "Arya Samaj", value: "Arya Samaj" },
    { label: "Asatru", value: "Asatru" },
    { label: "Asceticism", value: "Asceticism" },
    { label: "Assemblies of God", value: "Assemblies of God" },
    { label: "Assembly of Free Spirit Baptist Church", value: "Assembly of Free Spirit Baptist Church" },
    { label: "Atheist movement", value: "Atheist movement" },
    { label: "Babis religion", value: "Babis religion" },
    { label: "Bahaism", value: "Bahaism" },
    { label: "Baptist Church", value: "Baptist Church" },
    { label: "Black magic", value: "Black magic" },
    { label: "Brahma Kumaris", value: "Brahma Kumaris" },
    { label: "Brahmanism", value: "Brahmanism" },
    { label: "British Israelism", value: "British Israelism" },
    { label: "Buddhism", value: "Buddhism" },
    { label: "Bulgarian Orthodox Church", value: "Bulgarian Orthodox Church" },
    { label: "Calvinism", value: "Calvinism" },
    { label: "Catholic religion", value: "Catholic religion" },
    { label: "Celtic Christian Church", value: "Celtic Christian Church" },
    { label: "Celtic Orthodox Church", value: "Celtic Orthodox Church" },
    { label: "Celtic paganism", value: "Celtic paganism" },
    { label: "Central Asian Buddhist religion", value: "Central Asian Buddhist religion" },
    { label: "Chinese Evangelical Christian Church", value: "Chinese Evangelical Christian Church" },
    { label: "Chinese Buddhist religion", value: "Chinese Buddhist religion" },
    { label: "Christadelphian movement", value: "Christadelphian movement" },
    { label: "Christian Existentialism", value: "Christian Existentialism" },
    { label: "Christian Humanism", value: "Christian Humanism" },
    { label: "Christian Methodist Episcopal Church", value: "Christian Methodist Episcopal Church" },
    { label: "Christian Reformed Church", value: "Christian Reformed Church" },
    { label: "Christian Scientist religious movement", value: "Christian Scientist religious movement" },
    { label: "Christian Spiritualism", value: "Christian Spiritualism" },
    { label: "Christian religion", value: "Christian religion" },
    { label: "Church Universal and Triumphant", value: "Church Universal and Triumphant" },
    { label: "Church in Wales", value: "Church in Wales" },
    { label: "Church of England", value: "Church of England" },
    { label: "Church of God of Prophecy", value: "Church of God of Prophecy" },
    { label: "Church of Ireland", value: "Church of Ireland" },
    { label: "Church of Jesus Christ of Latter Day Saints", value: "Church of Jesus Christ of Latter Day Saints" },
    { label: "Church of Religious Science", value: "Church of Religious Science" },
    { label: "Church of Scientology", value: "Church of Scientology" },
    { label: "Church of Scotland", value: "Church of Scotland" },
    { label: "Church of the Brethren", value: "Church of the Brethren" },
    { label: "Church of the Nazarene", value: "Church of the Nazarene" },
    { label: "Comenianism", value: "Comenianism" },
    { label: "Confucianism", value: "Confucianism" },
    { label: "Congregationalist Church", value: "Congregationalist Church" },
    { label: "Conservative Baptist Church", value: "Conservative Baptist Church" },
    { label: "Conservative Jewish religion", value: "Conservative Jewish religion" },
    { label: "Coptic Church", value: "Coptic Church" },
    { label: "Deism", value: "Deism" },
    { label: "Divine Science Church", value: "Divine Science Church" },
    { label: "Doukhobor religion", value: "Doukhobor religion" },
    { label: "Druze religion", value: "Druze religion" },
    { label: "Eastern Catholic religion", value: "Eastern Catholic religion" },
    { label: "Eastern Christianity", value: "Eastern Christianity" },
    { label: "Eastern Orthodox Church", value: "Eastern Orthodox Church" },
    { label: "Eckankar religion", value: "Eckankar religion" },
    { label: "Eminist religion", value: "Eminist religion" },
    { label: "Ethiopian Church", value: "Ethiopian Church" },
    { label: "Evangelical Church", value: "Evangelical Church" },
    { label: "Exclusive Brethren", value: "Exclusive Brethren" },
    { label: "Free Christian Church", value: "Free Christian Church" },
    { label: "Free Church of Scotland", value: "Free Church of Scotland" },
    { label: "Free Evangelical Presbyterian Church", value: "Free Evangelical Presbyterian Church" },
    { label: "Free Presbyterian Church", value: "Free Presbyterian Church" },
    { label: "Free Will Baptist Church", value: "Free Will Baptist Church" },
    { label: "Goddess Tradition", value: "Goddess Tradition" },
    { label: "Greek Catholic Church", value: "Greek Catholic Church" },
    { label: "Greek Orthodox Church", value: "Greek Orthodox Church" },
    { label: "Haredi Judaism", value: "Haredi Judaism" },
    { label: "Hasidim", value: "Hasidim" },
    { label: "Hinduism", value: "Hinduism" },
    { label: "Hinduism, Buddhism AND/OR derivative", value: "Hinduism, Buddhism AND/OR derivative" },
    { label: "Humanism", value: "Humanism" },
    { label: "Humanistic Judaism", value: "Humanistic Judaism" },
    { label: "Hutterian Brethren", value: "Hutterian Brethren" },
    { label: "Independent Fundamental Christian Church", value: "Independent Fundamental Christian Church" },
    { label: "Infinite Way", value: "Infinite Way" },
    { label: "Islam", value: "Islam" },
    { label: "Islam AND/OR derivative", value: "Islam AND/OR derivative" },
    { label: "Isma'ilis religion", value: "Isma'ilis religion" },
    { label: "Jainism", value: "Jainism" },
    { label: "Japanese Buddhist religion", value: "Japanese Buddhist religion" },
    { label: "Jehovah's Witness religion", value: "Jehovah's Witness religion" },
    { label: "Judaic Christian", value: "Judaic Christian" },
    { label: "Judaism", value: "Judaism" },
    { label: "Kabbalah", value: "Kabbalah" },
    { label: "Krishna Consciousness Religious Movement", value: "Krishna Consciousness Religious Movement" },
    { label: "Lamaism", value: "Lamaism" },
    { label: "Liberal Jewish religion", value: "Liberal Jewish religion" },
    { label: "Liberal Protestant religion", value: "Liberal Protestant religion" },
    { label: "Lightworker", value: "Lightworker" },
    { label: "Lutheran Church", value: "Lutheran Church" },
    { label: "Mahayana Buddhist religion", value: "Mahayana Buddhist religion" },
    { label: "Maronite Church", value: "Maronite Church" },
    { label: "Mennonite Church", value: "Mennonite Church" },
    { label: "Messianic Judaism", value: "Messianic Judaism" },
    { label: "Methodist Church", value: "Methodist Church" },
    { label: "Mixed religion", value: "Mixed religion" },
    { label: "Moravian Church", value: "Moravian Church" },
    { label: "Mysticism", value: "Mysticism" },
    { label: "National Spiritualist Church", value: "National Spiritualist Church" },
    { label: "Native American Religion", value: "Native American Religion" },
    { label: "New Kadampa Tradition - International Kadampa Buddhist Union", value: "New Kadampa Tradition - International Kadampa Buddhist Union" },
    { label: "New Testament Church of God", value: "New Testament Church of God" },
    { label: "New religious movement", value: "New religious movement" },
    { label: "Nichiren Buddhism", value: "Nichiren Buddhism" },
    { label: "Nonconformist religion", value: "Nonconformist religion" },
    { label: "Occultism", value: "Occultism" },
    { label: "Old Catholic Church", value: "Old Catholic Church" },
    { label: "Open Brethren", value: "Open Brethren" },
    { label: "Open Episcopal Church", value: "Open Episcopal Church" },
    { label: "Orthodox Baptist Church", value: "Orthodox Baptist Church" },
    { label: "Orthodox Christian religion", value: "Orthodox Christian religion" },
    { label: "Orthodox Jewish Faith", value: "Orthodox Jewish Faith" },
    { label: "Paganism", value: "Paganism" },
    { label: "Pantheism", value: "Pantheism" },
    { label: "Para-religious movement", value: "Para-religious movement" },
    { label: "Pentecostal Free Will Baptist Church", value: "Pentecostal Free Will Baptist Church" },
    { label: "Pentecostalist religion", value: "Pentecostalist religion" },
    { label: "Peyote Religion", value: "Peyote Religion" },
    { label: "Pietist religion", value: "Pietist religion" },
    { label: "Plymouth Brethren religion", value: "Plymouth Brethren religion" },
    { label: "Presbyterian Church", value: "Presbyterian Church" },
    { label: "Primal society religion", value: "Primal society religion" },
    { label: "Primitive tribal spiritual belief", value: "Primitive tribal spiritual belief" },
    { label: "Protestant religion", value: "Protestant religion" },
    { label: "Pure Land Buddhism", value: "Pure Land Buddhism" },
    { label: "Quaker religion", value: "Quaker religion" },
    { label: "Radhasoami", value: "Radhasoami" },
    { label: "Rastafarian movement", value: "Rastafarian movement" },
    { label: "Reconstructionist Jewish religion", value: "Reconstructionist Jewish religion" },
    { label: "Reform Jewish Faith", value: "Reform Jewish Faith" },
    { label: "Reformed Church", value: "Reformed Church" },
    { label: "Reformed Presbyterian Church", value: "Reformed Presbyterian Church" },
    { label: "Reformed Protestant", value: "Reformed Protestant" },
    { label: "Religion of Japan, China AND/OR Persia", value: "Religion of Japan, China AND/OR Persia" },
    { label: "Rosicrucian Fellowship", value: "Rosicrucian Fellowship" },
    { label: "Rumanian Orthodox Church", value: "Rumanian Orthodox Church" },
    { label: "Russian Orthodox Church", value: "Russian Orthodox Church" },
    { label: "Salvation Army", value: "Salvation Army" },
    { label: "Santeria", value: "Santeria" },
    { label: "Satanism", value: "Satanism" },
    { label: "Scottish Episcopalian Church", value: "Scottish Episcopalian Church" },
    { label: "Scottish Protestant religion", value: "Scottish Protestant religion" },
    { label: "Serbian Orthodox Church", value: "Serbian Orthodox Church" },
    { label: "Seventh Day Adventist religion", value: "Seventh Day Adventist religion" },
    { label: "Seventh Day Baptist Church", value: "Seventh Day Baptist Church" },
    { label: "Seventh Day Pentecostal Assembly", value: "Seventh Day Pentecostal Assembly" },
    { label: "Shakti Hinduism", value: "Shakti Hinduism" },
    { label: "Shamanism", value: "Shamanism" },
    { label: "Shi'ite Muslim religion", value: "Shi'ite Muslim religion" },
    { label: "Syrian Orthodox Church", value: "Syrian Orthodox Church" },
    { label: "Taoism", value: "Taoism" },
    { label: "Theravada Buddhist religion", value: "Theravada Buddhist religion" },
    { label: "Tibetan Buddhist religion", value: "Tibetan Buddhist religion" },
    { label: "Transcendental Meditation", value: "Transcendental Meditation" },
    { label: "Trinitarian Humanism", value: "Trinitarian Humanism" },
    { label: "Ukrainian Catholic Church", value: "Ukrainian Catholic Church" },
    { label: "Ultimatism", value: "Ultimatism" },
    { label: "Unification Church Religious Movement", value: "Unification Church Religious Movement" },
    { label: "Unitarian Universalist Church", value: "Unitarian Universalist Church" },
    { label: "United Church of Canada", value: "United Church of Canada" },
    { label: "United Church of Christ", value: "United Church of Christ" },
    { label: "United Free Church of Scotland", value: "United Free Church of Scotland" },
    { label: "United Methodist Church", value: "United Methodist Church" },
    { label: "United Reform Church", value: "United Reform Church" },
    { label: "Universalism", value: "Universalism" },
    { label: "Vaishnava Hinduism", value: "Vaishnava Hinduism" },
    { label: "Vodun", value: "Vodun" },
    { label: "Waldensian - Methodist Church", value: "Waldensian - Methodist Church" },
    { label: "Western Buddhism", value: "Western Buddhism" },
    { label: "Western Christianity", value: "Western Christianity" },
    { label: "Witchcraft", value: "Witchcraft" },
    { label: "Yoruba", value: "Yoruba" },
    { label: "Zen Buddhism", value: "Zen Buddhism" },
    { label: "Zoroastrianism", value: "Zoroastrianism" },
    { label: "Zwinglianism", value: "Zwinglianism" },
    { label: "Not stated", value: "Not stated" },
];

export const clientsStatusOptions = [
    { label: "Active", value: "ACTIVE" },
    { label: "Inactive", value: "INACTIVE" },
    { label: "Temporarily Inactive", value: "TEMP_INACTIVE" },
];

export const clientsRiskLevelOptions = [
    { label: "Red", value: "RED" },
    { label: "Amber", value: "AMBER" },
    { label: "Green", value: "GREEN" },
];

export const getClientsClinicalMedicalSupportOptions = (clientName = "the client") => [
    { label: `We provide ${clientName}'s medicine support`, value: true },
    { label: `We do not provide ${clientName}'s medicine support`, value: false },
];

export const clientsFamilyInvolvementOptions = [
    { label: "Very Involved", value: "VERY_INVOLVED" },
    { label: "Involved", value: "INVOLVED" },
    { label: "Somewhat Involved", value: "SOMEWHAT_INVOLVED" },
    { label: "Not Involved", value: "NOT_INVOLVED" },
];

export const clientsContactMethodOptions = [
    { label: "Email", value: "EMAIL" },
    { label: "Phone", value: "PHONE" },
    { label: "Text", value: "TEXT" },
    { label: "Mail", value: "MAIL" },
];

export const clientsCarerPreferencesOptions = [
    { label: "Male", value: "MALE" },
    { label: "Female", value: "FEMALE" },
    { label: "Non-binary", value: "NON_BINARY" },
    { label: "No preferences", value: "NO_PREFERENCE" },
];

export const clientsSexOptions = [
    { label: "Male", value: "MALE" },
    { label: "Female", value: "FEMALE" },
    { label: "Indeterminate", value: "INDETERMINATE" },
    { label: "Rather not say", value: "NOT_SAY" },
];

export const clientsGenderOptions = [
    { label: "Woman", value: "FEMALE" },
    { label: "Man", value: "MALE" },
    { label: "Non-binary", value: "NON_BINARY" },
    { label: "Questioning or unsure", value: "QUESTIONING" },
    { label: "Prefer not to say", value: "NOT_SAY" },
];

export const clientsSexualOrientationOptions = [
    { label: "Heterosexual (straight)", value: "Heterosexual (straight)" },
    { label: "Gay or lesbian", value: "Gay or lesbian" },
    { label: "Bisexual", value: "Bisexual" },
    { label: "Pansexual", value: "Pansexual" },
    { label: "Asexual", value: "Asexual" },
    { label: "Queer", value: "Queer" },
    { label: "Questioning or unsure", value: "Questioning or unsure" },
    { label: "Prefer not to say", value: "Prefer not to say" },
];

export const clientsCommunicationSupportOptions = [
    { label: "Requires Specific Contact Method", value: "SPECIFIC_CONTACT_METHOD" },
    { label: "Requires Specific Information Format", value: "SPECIFIC_INFORMATION_FORMAT" },
    { label: "Requires Communication Professional", value: "COMMUNICATION_PROFESSIONAL" },
    { label: "Requires Communication Support", value: "COMMUNICATION_SUPPORT" },
];

export const clientsFundingOptions = [
    { label: "Local Authority", value: "LOCAL_AUTHORITY" },
    { label: "Private", value: "PRIVATE" },
    { label: "NHS", value: "NHS" },
    { label: "Other", value: "OTHER" },
];

export const enumMappings = {
    LOCAL_AUTHORITY: "Local Authority",
    PRIVATE: "Private",
    NHS: "NHS",
    OTHER: "Other",
    VERY_INVOLVED: "Very Involved",
    INVOLVED: "Involved",
    SOMEWHAT_INVOLVED: "Somewhat Involved",
    NOT_INVOLVED: "Not Involved",
    SPOUSE_PARTNER: "Spouse/Partner",
    SON_DAUGHTER: "Son/Daughter",
    PARENT: "Parent",
    SIBLING: "Sibling",
    OTHER_RELATIVE: "Other Relative",
    FRIEND: "Friend",
    NEIGHBOR: "Neighbor",
    NEXT_OF_KIN: "Next of Kin",
    EMERGENCY_CONTACT: "Emergency Contact",
    BOTH: "Both",
    DONT_KNOW: "Not Known",
};

export const getMedicationPrivacyOptions = (clientName = "the client") => [
    { label: `We provide ${clientName}’s medicine support`, value: true, description: "Carers must record each time they help with medication" },
    {
        label: `We do not provide ${clientName}’s medicine support`,
        value: false,
        description: `Carers are not required to record ${clientName} taking medication`,
    },
];

export const medicationChartListOptions = [
    { label: "Chart", value: "CHART" },
    { label: "List", value: "LIST" },
];
