import { test } from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import request from "supertest";
import { openDatabase, initializeSchema } from "../src/db.js";
import { createApp } from "../src/app.js";

test("Mobile carer visit workflow is assigned, audited and tenant scoped", async () => {
  const db=await openDatabase({driver:"pglite",dataDir:":memory:"}); await initializeSchema(db);
  const sent=[];
  const app=createApp({db,config:{production:false,jwtSecret:"mobile-test-secret-at-least-32-characters",frontendUrl:"http://localhost",corsOrigins:[],uploadDir:"./test-uploads"},mail:{send:async(m)=>sent.push(m)}});
  const {repo}=app.locals.ctx, agency=randomUUID(), otherAgency=randomUUID();
  for(const [id,name] of [[agency,"Care Agency"],[otherAgency,"Other Agency"]])
    await db.query("INSERT INTO node_agencies(id,name,business_type,phone,address_line1,city,postcode,country,timezone,terms_accepted_at) VALUES($1,$2,'HOME_CARE','01234567890','1 Test Street','Birmingham','B1 1AA','UK','Europe/London',CURRENT_TIMESTAMP)",[id,name]);
  const carer=await repo.save("UserEntity",{agencyId:agency,firstName:"Mobile",lastName:"Carer",email:"mobile@example.test",role:"CAREGIVER",isActive:true});
  const witness=await repo.save("UserEntity",{agencyId:agency,firstName:"Second",lastName:"Carer",email:"witness@example.test",role:"CAREGIVER",isActive:true});
  const admin=await repo.save("UserEntity",{agencyId:agency,firstName:"Care",lastName:"Manager",email:"manager@example.test",role:"ADMIN",isActive:true});
  const other=await repo.save("UserEntity",{agencyId:otherAgency,firstName:"Other",lastName:"Carer",email:"other@example.test",role:"CAREGIVER",isActive:true});
  const client=await repo.save("UserEntity",{agencyId:agency,firstName:"Care",lastName:"Client",email:"client@example.test",role:"USER",isActive:true});
  await repo.save("ClientCareTeamEntity",{client:client.id,carer:carer.id,viewAccess:true});
  const personalCare=await repo.save("ClientPersonalCareEntity",{user:client.id,assessmentSummaryOutcomes:"Prefers support after breakfast."});
  await repo.save("ClientPersonalCareAssessmentEntity",{personalCare:personalCare.id,bathing_washing_independence:{support:"One caregiver"},oral_hygiene_maintenance:{support:"Needs a soft toothbrush"},submittedAt:new Date().toISOString()});
  await repo.save("CarePlanRisksMitigationsEntity",{entityId:personalCare.id,entityType:"PERSONAL_CARE",risk:"Slips",mitigation:"Keep floor dry",riskLevel:"MEDIUM"});
  await repo.save("ClientMedicationEntity",{user:client.id,allergies:"Penicillin - severe rash"});
  await repo.save("UserPrimaryAddressEntity",{user:client.id,addressLine1:"1 Test Street",city:"Birmingham",postalCode:"B1 1AA",isPrimary:true,latitude:52.1,longitude:-1.5,checkinRadius:150});
  const category=await repo.save("ClientTaskCategoryEntity",{name:"Daily care",description:"Test category"});
  const task=await repo.save("ClientTaskEntity",{name:"Hydration check",description:"Offer water",clientTaskCategory:category.id});
  await repo.save("ClientTaskPlanEntity",{task:task.id,taskNameSnapshot:task.name,categoryNameSnapshot:category.name,user:client.id,details:"Offer water",isEssential:true,isAnyTime:true,sessions:[],frequency:"DAILY",selectedDays:[],startDate:"2026-01-01",timesPerDay:1,revision:1});
  await repo.save("ClientMedicationSchedulingEntity",{user:client.id,clientFirstName:"Care",clientLastName:"Client",medicationName:"Test medication",dose:"1 unit",route:"Topical",bodyMapData:"Left forearm",frequencyType:"DAILY",dailyTimes:1,timingPreference:"EXACT_TIME",exactTimes:{dose1:"09:30"},firstDoseDate:"2026-01-01",isStopped:false});
  const controlled=await repo.save("ClientMedicationSchedulingEntity",{user:client.id,clientFirstName:"Care",clientLastName:"Client",medicationName:"Controlled PRN",type:"PRN",dose:"1 tablet",route:"Oral",prnStartDate:"2026-01-01",timeBetweenDoses:"4",timeBetweenUnit:"hours",maxDoseCount:"1",maxDosePeriod:"24",maxDoseUnit:"hours",isStopped:false,isControlledDrug:true,requiresWitness:true,stockTrackingEnabled:true,stockQuantity:5,stockUnit:"tablets",lowStockThreshold:4});
  const visitId=randomUUID(); await db.query("INSERT INTO node_roster_visits(id,agency_id,client_id,staff_id,visit_date,start_time,end_time,title,notes,status,revision,created_by,updated_by) VALUES($1,$2,$3,$4,'2026-09-13','09:00','10:00','Morning care','','SCHEDULED',1,$4,$4)",[visitId,agency,client.id,carer.id]);
  await db.query("INSERT INTO node_roster_visits(id,agency_id,client_id,staff_id,visit_date,start_time,end_time,title,notes,status,revision,created_by,updated_by) VALUES($1,$2,$3,$4,'2026-09-14','11:00','12:00','Next day care','','SCHEDULED',1,$4,$4)",[randomUUID(),agency,client.id,witness.id]);
  const priorVisit=randomUUID();
  await db.query("INSERT INTO node_roster_visits(id,agency_id,client_id,staff_id,visit_date,start_time,end_time,title,notes,status,revision,created_by,updated_by) VALUES($1,$2,$3,$4,'2026-09-12','09:00','10:00','Prior care','','COMPLETED',1,$4,$4)",[priorVisit,agency,client.id,witness.id]);
  await db.query("INSERT INTO node_client_entries(id,agency_id,client_id,visit_id,kind,title,body,status,created_by,updated_by) VALUES($1,$2,$3,$4,'NOTE','Handover','Client preferred tea','RECORDED',$5,$5)",[randomUUID(),agency,client.id,priorVisit,witness.id]);
  await db.query("INSERT INTO node_roster_visits(id,agency_id,client_id,staff_id,visit_date,start_time,end_time,title,notes,status,revision,created_by,updated_by) VALUES($1,$2,$3,NULL,'2026-09-16','14:00','15:00','Unallocated visit','','DRAFT',1,$4,$4)",[randomUUID(),agency,client.id,admin.id]);
  await db.query("INSERT INTO node_roster_visits(id,agency_id,client_id,staff_id,visit_date,start_time,end_time,title,notes,status,revision,created_by,updated_by) VALUES($1,$2,$3,$4,'2026-09-21','14:00','15:00','Beyond seven days','','SCHEDULED',1,$4,$4)",[randomUUID(),agency,client.id,witness.id]);
  const tokenFor=async(u)=>{await app.locals.ctx.auth.requestLink(u.email);const link=sent.at(-1).text.match(/http[^\s]+/)[0];const [email,password]=Buffer.from(new URL(link).searchParams.get("token"),"base64url").toString().split(":");return (await app.locals.ctx.auth.exchange(email,password)).accessToken};
  const carerToken=await tokenFor(carer),witnessToken=await tokenFor(witness),otherToken=await tokenFor(other),adminToken=await tokenFor(admin);
  const call=(method,path,body,token=carerToken)=>{let r=request(app)[method](path).set("Authorization","Bearer "+token);if(body!==undefined)r=r.send(body);return r};
  try {
    assert.equal((await call("put","/api/mobile/me/profile",{firstName:"Mobile",lastName:"Carer",primaryPhone:"07123456789"})).status,200);
    assert.equal((await repo.get("UserEntity",carer.id)).primaryPhone,"07123456789");
    assert.equal((await call("put","/api/mobile/me/profile",{firstName:"A",lastName:"Carer"})).status,400);
    assert.equal((await call("get","/api/mobile/announcement")).body.results.data.message,"");
    assert.equal((await call("put","/api/mobile/announcement",{message:"Team briefing"})).status,403);
    assert.equal((await call("put","/api/mobile/announcement",{message:"Team briefing"},adminToken)).status,200);
    assert.equal((await call("get","/api/mobile/announcement")).body.results.data.message,"Team briefing");
    assert.equal((await call("get","/api/mobile/announcement",undefined,otherToken)).body.results.data.message,"");
    let leave=await call("post","/api/mobile/me/time-off-requests",{startDate:"2026-10-01",endDate:"2026-10-01",reason:"Personal appointment"});
    assert.equal(leave.status,201,JSON.stringify(leave.body));
    const leaveId=leave.body.results.data.id;
    assert.equal((await call("get","/api/mobile/me/time-off-requests")).body.results.data[0].status,"PENDING");
    assert.equal((await call("get","/api/team/time-off-requests")).status,403);
    const adminLeaveList=await call("get","/api/team/time-off-requests",undefined,adminToken);
    assert.equal(adminLeaveList.status,200,JSON.stringify(adminLeaveList.body));
    assert.equal(adminLeaveList.body.results.data.some((entry)=>entry.id===leaveId),true);
    assert.equal((await call("post",`/api/team/time-off-requests/${leaveId}/decision`,{decision:"APPROVED"},adminToken)).status,200);
    assert.equal((await call("get","/api/mobile/me/time-off-requests")).body.results.data[0].status,"APPROVED");
    assert.equal((await repo.find("TeamAbsenceEntity",{user:carer.id})).length,1);
    const availability=await call("post","/api/mobile/me/availability-requests",{startDate:"2026-10-05",endDate:"2026-10-06",startTime:"08:00",endTime:"18:00",reason:"Extra hours"});
    assert.equal(availability.status,201,JSON.stringify(availability.body));
    const availabilityId=availability.body.results.data.id;
    assert.equal((await call("post","/api/mobile/me/availability-requests",{startDate:"2026-10-05",endDate:"2026-10-06",startTime:"08:00",endTime:"18:00"})).status,409);
    assert.equal((await call("get","/api/team/availability-requests")).status,403);
    const adminAvailabilityList=await call("get","/api/team/availability-requests",undefined,adminToken);
    assert.equal(adminAvailabilityList.status,200,JSON.stringify(adminAvailabilityList.body));
    assert.equal(adminAvailabilityList.body.results.data.some((entry)=>entry.id===availabilityId),true);
    assert.equal((await call("post",`/api/team/availability-requests/${availabilityId}/decision`,{decision:"APPROVED"},otherToken)).status,403);
    assert.equal((await call("post",`/api/team/availability-requests/${availabilityId}/decision`,{decision:"APPROVED"},adminToken)).status,200);
    assert.equal((await call("post",`/api/team/availability-requests/${availabilityId}/decision`,{decision:"APPROVED"},adminToken)).status,409);
    assert.equal((await call("get","/api/mobile/me/availability-requests")).body.results.data[0].status,"APPROVED");
    assert.equal((await repo.find("TeamAvailabilityEntity",{user:carer.id})).some((a)=>a.startDate==="2026-10-05"&&a.endDate==="2026-10-06"),true);
    assert.equal((await call("get","/api/mobile/me/timesheet?from=2026-09-01&to=2026-09-30")).status,200);
    assert.equal((await call("get","/api/mobile/me/timesheet?from=2026-01-01&to=2026-09-30")).status,400);
    assert.equal((await call("get","/api/mobile/me/timesheet?from=2026-09-01&to=2026-09-30",undefined,adminToken)).status,403);
    const overview=await call("get",`/api/mobile/clients/${client.id}/care-overview`);
    assert.equal(overview.status,200,JSON.stringify(overview.body));
    assert.equal(overview.body.results.data.sections.find((section)=>section.key==="personal-care").summary,"Prefers support after breakfast.");
    assert.match(overview.body.results.data.sections.find((section)=>section.key==="personal-care").assessment[0].value,/One caregiver/);
    assert.equal(overview.body.results.data.sections.find((section)=>section.key==="personal-care").assessment.some((item)=>item.label==="oral hygiene maintenance"&&item.value.includes("Needs a soft toothbrush")),true);
    const prnLimits={timeBetweenDoses:4,timeBetweenUnit:"hours",maxDoseCount:1,maxDosePeriod:24,maxDoseUnit:"hours"};
    assert.equal((await call("put",`/api/mobile/admin/medication/${controlled.id}/prn-limits`,prnLimits)).status,403);
    assert.equal((await call("put",`/api/mobile/admin/medication/${controlled.id}/prn-limits`,prnLimits,adminToken)).status,200);
    assert.equal((await call("put",`/api/mobile/admin/medication/${controlled.id}/prn-limits`,{...prnLimits,maxDoseCount:0},adminToken)).status,400);
    assert.equal(overview.body.results.data.sections.find((section)=>section.key==="personal-care").risks[0].risk,"Slips");
    assert.equal((await call("get",`/api/mobile/clients/${client.id}/care-overview`,undefined,otherToken)).status,404);
    const handover=await call("get",`/api/mobile/clients/${client.id}/handover?page=1`);
    assert.equal(handover.status,200,JSON.stringify(handover.body));
    assert.equal(handover.body.results.data.items[0].body,"Client preferred tea");
    assert.equal(handover.body.results.data.items[0].recordedBy,"Second Carer");
    assert.equal((await call("get",`/api/mobile/clients/${client.id}/handover?page=0`)).status,400);
    assert.equal((await call("get",`/api/mobile/clients/${client.id}/handover`,undefined,otherToken)).status,404);
    await db.query("INSERT INTO node_roster_visits(id,agency_id,client_id,staff_id,visit_date,start_time,end_time,title,notes,status,revision,created_by,updated_by) VALUES($1,$2,$3,$4,CURRENT_DATE,'15:00','16:00','Assigned care','','SCHEDULED',1,$4,$4)",[randomUUID(),agency,client.id,witness.id]);
    assert.equal((await call("get",`/api/client/get-client/${client.id}`,undefined,witnessToken)).status,200);
    const assignedClients=await call("post","/api/client/get-all-clients",{search:"Care",page:1,size:20,isActive:true},witnessToken);
    assert.equal(assignedClients.status,200,JSON.stringify(assignedClients.body));
    assert.equal(assignedClients.body.results.data.users.some((person)=>person.id===client.id),true);
    await repo.save("ClientCareTeamEntity",{client:client.id,carer:witness.id,viewAccess:false,revokeViewaccess:true});
    assert.equal((await call("get",`/api/client/get-client/${client.id}`,undefined,witnessToken)).status,403);
    const revokedClients=await call("post","/api/client/get-all-clients",{search:"Care",page:1,size:20,isActive:true},witnessToken);
    assert.equal(revokedClients.body.results.data.users.some((person)=>person.id===client.id),false);
    let detailResponse=await call("get",`/api/mobile/visits/${visitId}`); assert.equal(detailResponse.status,200); assert.equal(detailResponse.body.results.data.tasks.length,1); assert.equal(detailResponse.body.results.data.medication.length,2); assert.equal(detailResponse.body.results.data.allergyInformation,"Penicillin - severe rash"); assert.equal(detailResponse.body.results.data.careOverview.find((section)=>section.key==="personal-care").risks[0].risk,"Slips"); assert.equal(detailResponse.body.results.data.nextVisit.caregiverName,"Second Carer"); assert.equal(detailResponse.body.results.data.nextVisit.date,"2026-09-14"); assert.equal(detailResponse.body.results.data.tomorrowVisits[0].caregiverName,"Second Carer"); assert.equal(detailResponse.body.results.data.upcomingVisits.length,2); assert.equal(detailResponse.body.results.data.upcomingVisits[1].caregiverName,"Not yet allocated"); assert.equal(detailResponse.body.results.data.previousNotes[0].body,"Client preferred tea"); const regular=detailResponse.body.results.data.medication.find((m)=>m.name==="Test medication"); assert.equal(regular.dose,"1 unit"); assert.equal(regular.bodyMapData,"Left forearm"); assert.deepEqual(regular.dueSlots,["09:30"]); assert.equal(detailResponse.body.results.data.witnesses.some((w)=>w.id===witness.id),true);
    assert.equal((await call("get",`/api/mobile/visits/${visitId}`,undefined,otherToken)).status,404);
    const ukToday=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/London",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
    const futureDate=(days)=>new Date(Date.parse(ukToday)+days*86400000).toISOString().slice(0,10);
    const visibleVisit=randomUUID(),hiddenVisit=randomUUID();
    for(const [id,date] of [[visibleVisit,futureDate(6)],[hiddenVisit,futureDate(7)]])
      await db.query("INSERT INTO node_roster_visits(id,agency_id,client_id,staff_id,visit_date,start_time,end_time,title,notes,status,revision,created_by,updated_by) VALUES($1,$2,$3,$4,$5,'16:00','17:00','Future care','','SCHEDULED',1,$4,$4)",[id,agency,client.id,carer.id,date]);
    const rota=await call("get",`/api/roster/visits?from=${ukToday}&to=${futureDate(7)}`);
    assert.equal(rota.status,200);
    assert.equal(rota.body.results.data.visits.some((item)=>item.id===visibleVisit),true);
    assert.equal(rota.body.results.data.visits.some((item)=>item.id===hiddenVisit),false);
    assert.equal((await call("get",`/api/mobile/visits/${hiddenVisit}`)).status,404);
    assert.equal((await call("get",`/api/mobile/visits/${hiddenVisit}`,undefined,adminToken)).status,200);
    assert.equal((await call("post",`/api/mobile/visits/${visitId}/entries`,{clientEventId:randomUUID(),kind:"NOTE",title:"Too early",body:"Must check in first",status:"RECORDED",category:""})).status,409);
    let r=await call("post",`/api/mobile/visits/${visitId}/attendance`,{clientEventId:randomUUID(),event:"CHECK_IN",latitude:null,longitude:null,accuracy:null});assert.equal(r.status,400);
    const checkInEvent=randomUUID();
    r=await call("post",`/api/mobile/visits/${visitId}/attendance`,{clientEventId:checkInEvent,event:"CHECK_IN",latitude:52.1,longitude:-1.5,accuracy:8});assert.equal(r.status,200,JSON.stringify(r.body)); assert.equal(r.body.results.data.withinRadius,true); assert.equal(r.body.results.data.locationStatus,"VERIFIED");
    r=await call("post",`/api/mobile/visits/${visitId}/attendance`,{clientEventId:checkInEvent,event:"CHECK_IN",latitude:52.1,longitude:-1.5,accuracy:8});assert.equal(r.status,200,JSON.stringify(r.body));
    const locationEvent=randomUUID(),recordedAt=new Date().toISOString();
    r=await call("post",`/api/mobile/visits/${visitId}/locations`,{clientEventId:locationEvent,latitude:52.1001,longitude:-1.5001,accuracy:12,recordedAt});assert.equal(r.status,201,JSON.stringify(r.body));assert.equal(r.body.results.data.withinRadius,true);
    r=await call("post",`/api/mobile/visits/${visitId}/locations`,{clientEventId:locationEvent,latitude:52.1001,longitude:-1.5001,accuracy:12,recordedAt});assert.equal(r.status,200,JSON.stringify(r.body));
    const medicationId=regular.id,clientEventId=randomUUID();
    r=await call("post",`/api/mobile/visits/${visitId}/attendance`,{clientEventId:randomUUID(),event:"CHECK_OUT",latitude:52.1,longitude:-1.5,accuracy:9});assert.equal(r.status,409);
    r=await call("post",`/api/mobile/visits/${visitId}/medication-administrations`,{clientEventId,medicationId,outcome:"ADMINISTERED",slot:"09:30",doseGiven:"1 unit",reason:"",note:"Taken with water",prnEffect:"",witnessedBy:null,occurredAt:new Date().toISOString()});assert.equal(r.status,400,JSON.stringify(r.body));
    r=await call("post",`/api/mobile/visits/${visitId}/medication-administrations`,{clientEventId,medicationId,outcome:"ADMINISTERED",slot:"09:30",doseGiven:"1 unit",reason:"",note:"Taken with water",prnEffect:"",witnessedBy:null,allergyAcknowledged:true,occurredAt:new Date().toISOString()});assert.equal(r.status,400,JSON.stringify(r.body));
    r=await call("post",`/api/mobile/visits/${visitId}/medication-administrations`,{clientEventId,medicationId,outcome:"ADMINISTERED",slot:"09:30",doseGiven:"1 unit",reason:"",note:"Taken with water",prnEffect:"",witnessedBy:null,allergyAcknowledged:true,bodyMapAcknowledged:true,occurredAt:new Date().toISOString()});assert.equal(r.status,201,JSON.stringify(r.body));assert.equal(r.body.results.data.body_map_acknowledged,true);
    r=await call("post",`/api/mobile/visits/${visitId}/medication-administrations`,{clientEventId,medicationId,outcome:"ADMINISTERED",slot:"09:30",doseGiven:"1 unit",reason:"",note:"Taken with water",prnEffect:"",witnessedBy:null,allergyAcknowledged:true,occurredAt:new Date().toISOString()});assert.equal(r.status,200,JSON.stringify(r.body));
    r=await call("post",`/api/mobile/visits/${visitId}/medication-administrations`,{clientEventId:randomUUID(),medicationId,outcome:"REFUSED",slot:"09:30",doseGiven:"",reason:"Client declined",note:"Senior informed",prnEffect:"",witnessedBy:null,occurredAt:new Date().toISOString()});assert.equal(r.status,409);
    r=await call("post",`/api/mobile/visits/${visitId}/medication-administrations`,{clientEventId:randomUUID(),medicationId,outcome:"REFUSED",slot:"10:00",doseGiven:"",reason:"",note:"",prnEffect:"",witnessedBy:null,occurredAt:new Date().toISOString()});assert.equal(r.status,400);
    r=await call("post",`/api/mobile/visits/${visitId}/medication-administrations`,{clientEventId:randomUUID(),medicationId,outcome:"REFUSED",slot:"10:00",doseGiven:"",reason:"Client declined",note:"Senior informed",prnEffect:"",witnessedBy:null,occurredAt:new Date().toISOString()});assert.equal(r.status,201,JSON.stringify(r.body));
    const controlledEvent=randomUUID();
    r=await call("post",`/api/mobile/visits/${visitId}/medication-administrations`,{clientEventId:controlledEvent,medicationId:controlled.id,outcome:"PRN_ADMINISTERED",slot:"PRN",doseGiven:"1 tablet",quantityGiven:1,reason:"",note:"Pain reported",prnEffect:"Awaiting review",witnessedBy:null,occurredAt:new Date().toISOString()});assert.equal(r.status,400);
    const firstPrnTime=new Date(Date.now()-6*3600000).toISOString();
    r=await call("post",`/api/mobile/visits/${visitId}/medication-administrations`,{clientEventId:controlledEvent,medicationId:controlled.id,outcome:"PRN_ADMINISTERED",slot:"PRN",doseGiven:"1 tablet",quantityGiven:1,reason:"",note:"Pain reported",prnEffect:"Awaiting review",witnessedBy:witness.id,allergyAcknowledged:true,occurredAt:firstPrnTime});assert.equal(r.status,201,JSON.stringify(r.body)); const controlledAdministration=r.body.results.data.id;
    const repeatPrn={clientEventId:randomUUID(),medicationId:controlled.id,outcome:"PRN_ADMINISTERED",slot:"PRN repeat",doseGiven:"1 tablet",quantityGiven:1,reason:"",note:"Pain reported again",prnEffect:"Awaiting review",witnessedBy:witness.id,allergyAcknowledged:true,occurredAt:new Date(Date.parse(firstPrnTime)+3600000).toISOString()};
    r=await call("post",`/api/mobile/visits/${visitId}/medication-administrations`,repeatPrn);assert.equal(r.status,409);assert.match(r.body.message,/too close/i);
    r=await call("post",`/api/mobile/visits/${visitId}/medication-administrations`,{...repeatPrn,clientEventId:randomUUID(),occurredAt:new Date().toISOString()});assert.equal(r.status,409);assert.match(r.body.message,/maximum/i);
    assert.equal(Number((await repo.get("ClientMedicationSchedulingEntity",controlled.id)).stockQuantity),4);
    r=await call("post",`/api/medication-administrations/${controlledAdministration}/corrections`,{reason:"Effect reviewed after thirty minutes",replacement:{note:"Pain reduced after 30 minutes"}},adminToken);assert.equal(r.status,201,JSON.stringify(r.body));
    const noteEvent=randomUUID();
    r=await call("post",`/api/mobile/visits/${visitId}/entries`,{clientEventId:noteEvent,kind:"NOTE",title:"Visit note",body:"Client comfortable",status:"RECORDED",category:""});assert.equal(r.status,201,JSON.stringify(r.body));
    const webFeed=(await call("get",`/api/clients/${client.id}/feed?page=1`,undefined,adminToken)).body.results.data;
    assert.equal(webFeed.items.some((item)=>item.title==="Visit note"&&item.body==="Client comfortable"),true);
    r=await call("post",`/api/mobile/visits/${visitId}/entries`,{clientEventId:randomUUID(),kind:"OBSERVATION",title:"Fluids",body:"Offered water with lunch",status:"RECORDED",category:"FLUIDS"});assert.equal(r.status,201,JSON.stringify(r.body));
    const observationFeed=(await call("get",`/api/clients/${client.id}/feed?page=1`,undefined,adminToken)).body.results.data;
    assert.equal(observationFeed.items.some((item)=>item.kind==="OBSERVATION"&&item.body==="Offered water with lunch"),true);
    const clinicalEvent=randomUUID();
    r=await call("post",`/api/mobile/visits/${visitId}/entries`,{clientEventId:clinicalEvent,kind:"OBSERVATION",title:"Clinical: Blood pressure",body:"120/80 mmHg",status:"RECORDED",category:"CLINICAL_BLOOD_PRESSURE",clinical:{type:"BLOOD_PRESSURE",value:"invalid"}});assert.equal(r.status,400);
    r=await call("post",`/api/mobile/visits/${visitId}/entries`,{clientEventId:clinicalEvent,kind:"OBSERVATION",title:"Clinical: Blood pressure",body:"120/80 mmHg",status:"RECORDED",category:"CLINICAL_BLOOD_PRESSURE",clinical:{type:"BLOOD_PRESSURE",value:"120/80"}});assert.equal(r.status,201,JSON.stringify(r.body));
    assert.deepEqual((await db.query("SELECT reading,unit FROM node_clinical_observations WHERE entry_id=$1",[r.body.results.data.id])).rows[0],{reading:{systolic:120,diastolic:80},unit:"mmHg"});
    r=await call("post",`/api/mobile/visits/${visitId}/entries`,{clientEventId:randomUUID(),kind:"OBSERVATION",title:"Skin: Front Arm",body:"Small bruise noted",status:"RECORDED",category:"SKIN_INTEGRITY"});assert.equal(r.status,201,JSON.stringify(r.body));
    const updatedWebFeed=(await call("get",`/api/clients/${client.id}/feed?page=1`,undefined,adminToken)).body.results.data;
    assert.equal(updatedWebFeed.items.some((item)=>item.category==="CLINICAL_BLOOD_PRESSURE"&&item.body==="120/80 mmHg"),true);
    assert.equal(updatedWebFeed.items.some((item)=>item.category==="SKIN_INTEGRITY"&&item.body==="Small bruise noted"),true);
    r=await call("post",`/api/mobile/visits/${visitId}/entries`,{clientEventId:noteEvent,kind:"NOTE",title:"Visit note",body:"Client comfortable",status:"RECORDED",category:""});assert.equal(r.status,200,JSON.stringify(r.body));
    r=await call("post",`/api/mobile/visits/${visitId}/entries`,{clientEventId:randomUUID(),kind:"ALERT",title:"Incident reported",body:"Minor concern escalated",status:"OPEN",category:"INCIDENT"});assert.equal(r.status,201);
    assert.equal(sent.some((message)=>message.subject==="Care concern: Incident reported: Care Client"&&message.to?.includes("manager@example.test")),true);
    r=await call("post",`/api/mobile/visits/${visitId}/attendance`,{clientEventId:randomUUID(),event:"CHECK_OUT",latitude:52.1,longitude:-1.5,accuracy:9});assert.equal(r.status,409);
    r=await call("post",`/api/mobile/visits/${visitId}/entries`,{clientEventId:randomUUID(),kind:"ACTIVITY",title:"Hydration check",body:"Completed during visit",status:"COMPLETED",category:(await repo.find("ClientTaskPlanEntity",{user:client.id}))[0].id});assert.equal(r.status,201);
    const photoEvent=randomUUID();
    r=await request(app).post(`/api/mobile/visits/${visitId}/photos`).set("Authorization","Bearer "+carerToken).field("clientEventId",photoEvent).field("caption","Dummy care evidence").field("latitude","52.1").field("longitude","-1.5").field("accuracy","9").field("capturedAt",new Date().toISOString()).attach("photo",Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64"),{filename:"dummy.png",contentType:"image/png"});assert.equal(r.status,201,JSON.stringify(r.body));
    const checkOutEvent=randomUUID();
    r=await call("post",`/api/mobile/visits/${visitId}/attendance`,{clientEventId:checkOutEvent,event:"CHECK_OUT",latitude:52.1,longitude:-1.5,accuracy:9});assert.equal(r.status,200);
    r=await request(app).post(`/api/mobile/visits/${visitId}/photos`).set("Authorization","Bearer "+carerToken).field("clientEventId",photoEvent);assert.equal(r.status,200,JSON.stringify(r.body));
    r=await call("post",`/api/mobile/visits/${visitId}/entries`,{clientEventId:noteEvent,kind:"NOTE",title:"Visit note",body:"Client comfortable",status:"RECORDED",category:""});assert.equal(r.status,200,JSON.stringify(r.body));
    r=await call("post",`/api/mobile/visits/${visitId}/medication-administrations`,{clientEventId,medicationId,outcome:"ADMINISTERED",slot:"09:30",doseGiven:"1 unit",reason:"",note:"Taken with water",prnEffect:"",witnessedBy:null,allergyAcknowledged:true,bodyMapAcknowledged:true,occurredAt:new Date().toISOString()});assert.equal(r.status,200,JSON.stringify(r.body));
    r=await call("post","/api/mobile/me/travel-claims",{visitId,miles:3.5,minutes:25,note:"Travel from previous visit"});assert.equal(r.status,201,JSON.stringify(r.body));
    const travelClaimId=r.body.results.data.id;
    assert.equal((await call("get","/api/mobile/admin/travel-claims")).status,403);
    assert.equal((await call("post",`/api/mobile/admin/travel-claims/${travelClaimId}/decision`,{decision:"APPROVED"})).status,403);
    assert.equal((await call("post",`/api/mobile/admin/travel-claims/${travelClaimId}/decision`,{decision:"APPROVED"},adminToken)).status,200);
    assert.equal((await call("post",`/api/mobile/admin/travel-claims/${travelClaimId}/decision`,{decision:"APPROVED"},adminToken)).status,409);
    const timesheet=(await call("get","/api/mobile/me/timesheet?from=2026-09-01&to=2026-09-30")).body.results.data;
    assert.equal(timesheet.visits.some((visit)=>visit.id===visitId&&visit.status==="COMPLETED"),true);
    assert.equal(timesheet.travelMinutes,25);
    assert.equal(timesheet.miles,3.5);
    assert.equal(timesheet.visits.find((visit)=>visit.id===visitId).travelClaimStatus,"APPROVED");
    assert.equal((await call("post",`/api/mobile/visits/${visitId}/entries`,{clientEventId:randomUUID(),kind:"NOTE",title:"Too late",body:"Visit is complete",status:"RECORDED",category:""})).status,409);
    r=await call("post",`/api/mobile/visits/${visitId}/attendance`,{clientEventId:checkOutEvent,event:"CHECK_OUT",latitude:52.1,longitude:-1.5,accuracy:9});assert.equal(r.status,200);
    const detail=(await call("get",`/api/mobile/visits/${visitId}`)).body.results.data;
    assert.equal(detail.visit.status,"COMPLETED"); assert.equal(detail.attendance.length,2); assert.equal(detail.locationTrail.length,1); assert.equal(detail.medicationAdministrations.length,3); assert.equal(detail.medicationAdministrations.some((a)=>a.outcome==="ADMINISTERED"),true); assert.equal(detail.medicationAdministrations.some((a)=>a.outcome==="REFUSED"),true); assert.equal(detail.medicationAdministrations.find((a)=>a.id===controlledAdministration).corrections.length,1); assert.equal(detail.entries.length,9); assert.equal(detail.entries.some((e)=>e.category==="MEDICATION"&&e.kind==="ALERT"),true); assert.equal(detail.entries.some((e)=>e.category==="MEDICATION_STOCK"&&e.kind==="ALERT"),true); assert.equal(detail.attachments.length,1); assert.equal(detail.entries.some((e)=>e.title==="Caregiver arrived"&&e.kind==="NOTE"&&e.status==="RECORDED"),true); assert.equal(sent.filter((m)=>m.subject==="Caregiver checked in: Care Client").length,1); assert.equal(sent.filter((m)=>m.subject==="Caregiver checked out: Care Client").length,1); assert.equal(sent.some((m)=>m.to?.includes("client@example.test")),false);
    const outsideVisit=randomUUID();
    await db.query("INSERT INTO node_roster_visits(id,agency_id,client_id,staff_id,visit_date,start_time,end_time,title,notes,status,revision,created_by,updated_by) VALUES($1,$2,$3,$4,'2026-09-13','18:00','19:00','Exception test','','SCHEDULED',1,$4,$4)",[outsideVisit,agency,client.id,carer.id]);
    const clientQrCode=randomUUID();
    await repo.save("ClientSettingsEntity",{user:client.id,qrCodeCheckIn:true,qrCodeId:clientQrCode});
    assert.equal((await call("get",`/api/mobile/visits/${outsideVisit}`)).body.results.data.qrCheckInRequired,true);
    const outsidePayload={clientEventId:randomUUID(),event:"CHECK_IN",latitude:52.2,longitude:-1.5,accuracy:9,locationExceptionReason:"Client requested meeting at a nearby venue"};
    assert.equal((await call("post",`/api/mobile/visits/${outsideVisit}/attendance`,outsidePayload)).status,400);
    assert.equal((await call("post",`/api/mobile/visits/${outsideVisit}/attendance`,{...outsidePayload,qrCode:randomUUID()})).status,403);
    const outside=await call("post",`/api/mobile/visits/${outsideVisit}/attendance`,{...outsidePayload,qrCode:clientQrCode});
    assert.equal(outside.status,200);
    assert.equal(outside.body.results.data.qrVerified,true);
    assert.equal(outside.body.results.data.locationStatus,"OUTSIDE_RADIUS");
    assert.equal((await db.query("SELECT source FROM node_visit_attendance WHERE visit_id=$1",[outsideVisit])).rows[0].source,"QR");
    assert.match((await db.query("SELECT body FROM node_client_entries WHERE visit_id=$1 AND title='Caregiver arrived outside check-in radius'",[outsideVisit])).rows[0].body,/Client requested meeting/);
    const qrExceptionVisit=randomUUID();
    await db.query("INSERT INTO node_roster_visits(id,agency_id,client_id,staff_id,visit_date,start_time,end_time,title,notes,status,revision,created_by,updated_by) VALUES($1,$2,$3,$4,'2026-09-13','20:00','21:00','Missing QR test','','SCHEDULED',1,$4,$4)",[qrExceptionVisit,agency,client.id,carer.id]);
    const exceptionPayload={clientEventId:randomUUID(),event:"CHECK_IN",latitude:52.1,longitude:-1.5,accuracy:8};
    assert.equal((await call("post",`/api/mobile/visits/${qrExceptionVisit}/attendance`,exceptionPayload)).status,400);
    assert.equal((await call("post",`/api/mobile/visits/${qrExceptionVisit}/attendance`,{...exceptionPayload,qrUnavailableReason:"Missing"})).status,400);
    assert.equal((await call("post",`/api/mobile/visits/${qrExceptionVisit}/attendance`,{...exceptionPayload,qrCode:randomUUID(),qrUnavailableReason:"Printed code is missing from the home"})).status,403);
    const qrException=await call("post",`/api/mobile/visits/${qrExceptionVisit}/attendance`,{...exceptionPayload,qrUnavailableReason:"Printed code is missing from the home"});
    assert.equal(qrException.status,200,JSON.stringify(qrException.body));
    assert.equal(qrException.body.results.data.qrVerified,false);
    assert.equal(qrException.body.results.data.qrException,true);
    assert.equal((await db.query("SELECT source FROM node_visit_attendance WHERE visit_id=$1",[qrExceptionVisit])).rows[0].source,"QR_EXCEPTION");
    assert.equal((await db.query("SELECT body FROM node_client_entries WHERE visit_id=$1 AND category='QR_EXCEPTION'",[qrExceptionVisit])).rows[0].body,"Printed code is missing from the home");
    assert.equal(sent.some((m)=>m.subject==="QR check-in exception requires review: Care Client"&&m.text.includes("Printed code is missing from the home")),true);
    const overrideVisit=randomUUID();await db.query("INSERT INTO node_roster_visits(id,agency_id,client_id,staff_id,visit_date,start_time,end_time,title,notes,status,revision,created_by,updated_by) VALUES($1,$2,$3,$4,'2026-09-13','09:00','10:00','Override test','','SCHEDULED',1,$4,$4)",[overrideVisit,agency,client.id,carer.id]);
    r=await call("post",`/api/mobile/visits/${overrideVisit}/attendance`,{clientEventId:randomUUID(),event:"CHECK_IN",latitude:52.1,longitude:-1.5,accuracy:8,qrCode:clientQrCode},adminToken);assert.equal(r.status,200);
    r=await call("post",`/api/mobile/visits/${overrideVisit}/attendance`,{clientEventId:randomUUID(),event:"CHECK_OUT",latitude:52.1,longitude:-1.5,accuracy:8,completionOverrideReason:"Emergency evacuation required early completion"},adminToken);assert.equal(r.status,200,JSON.stringify(r.body));
    assert.equal((await db.query("SELECT count(*)::int AS count FROM node_client_entries WHERE visit_id=$1 AND title='Visit completion override'",[overrideVisit])).rows[0].count,1);
    const overrideLog=(await call("get","/api/care-log?from=2026-09-13&to=2026-09-13",undefined,adminToken)).body.results.data.items.find((item)=>item.id===overrideVisit); assert.equal(overrideLog.overrides,1);
    assert.equal((await call("post","/api/mobile/note-assist",{text:"Client refused medication. Senior carer was informed."})).body.results.data.attention.length,1);
  } finally { await db.close(); }
});

test("100-metre arrival alert is accurate, assigned and sent once to administrators", async () => {
  const db=await openDatabase({driver:"pglite",dataDir:":memory:"}); await initializeSchema(db);
  const sent=[];
  const app=createApp({db,config:{production:false,jwtSecret:"mobile-test-secret-at-least-32-characters",frontendUrl:"http://localhost",corsOrigins:[],uploadDir:"./test-uploads"},mail:{send:async(message)=>sent.push(message)}});
  const {repo}=app.locals.ctx,agency=randomUUID();
  const caregiver=await repo.save("UserEntity",{agencyId:agency,firstName:"First",lastName:"Carer",email:"first@example.test",role:"CAREGIVER",isActive:true});
  const other=await repo.save("UserEntity",{agencyId:agency,firstName:"Other",lastName:"Carer",email:"other@example.test",role:"CAREGIVER",isActive:true});
  await repo.save("UserEntity",{agencyId:agency,firstName:"Care",lastName:"Manager",email:"manager@example.test",role:"ADMIN",isActive:true});
  await repo.save("UserEntity",{agencyId:agency,firstName:"Central",lastName:"Admin",email:"central@example.test",role:"SUPERADMIN",isActive:true});
  await repo.save("UserEntity",{agencyId:randomUUID(),firstName:"Other",lastName:"Owner",email:"owner-other@example.test",role:"SUPERADMIN",isActive:true});
  const client=await repo.save("UserEntity",{agencyId:agency,firstName:"Test",lastName:"Client",email:"client@example.test",role:"USER",isActive:true});
  await repo.save("UserPrimaryAddressEntity",{user:client.id,isPrimary:true,latitude:52.1,longitude:-1.5,checkinRadius:150});
  const visitId=randomUUID(),date=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/London",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
  await db.query("INSERT INTO node_roster_visits(id,agency_id,client_id,staff_id,visit_date,start_time,end_time,title,notes,status,revision,created_by,updated_by) VALUES($1,$2,$3,$4,$5,'09:00','10:00','Visit','','SCHEDULED',1,$4,$4)",[visitId,agency,client.id,caregiver.id,date]);
  const tokenFor=async(user)=>{await app.locals.ctx.auth.requestLink(user.email);const link=sent.at(-1).text.match(/http[^\s]+/)[0];const [email,password]=Buffer.from(new URL(link).searchParams.get("token"),"base64url").toString().split(":");return (await app.locals.ctx.auth.exchange(email,password)).accessToken};
  const token=await tokenFor(caregiver),otherToken=await tokenFor(other);
  const report=(body,bearer=token)=>request(app).post(`/api/mobile/visits/${visitId}/proximity`).set("Authorization","Bearer "+bearer).send(body);
  try {
    const near={latitude:52.1,longitude:-1.5,accuracy:10};
    assert.equal((await report(near,otherToken)).status,404);
    assert.equal((await report({...near,accuracy:150})).body.results.data.notified,false);
    assert.equal((await report({...near,latitude:52.11})).body.results.data.notified,false);
    const first=await report(near);assert.equal(first.status,201,JSON.stringify(first.body));assert.equal(first.body.results.data.notified,true);
    const again=await report(near);assert.equal(again.status,200);assert.equal(again.body.results.data.notified,false);
    assert.equal(sent.filter((message)=>message.subject==="Caregiver within 100 metres: Test Client").length,1);
    const arrival=sent.find((message)=>message.subject==="Caregiver within 100 metres: Test Client");
    assert.deepEqual(arrival.to,["manager@example.test"]);
    assert.equal(sent.some((message)=>message.to?.includes("client@example.test")),false);
    assert.equal((await db.query("SELECT count(*)::int AS count FROM node_client_entries WHERE visit_id=$1 AND category='PROXIMITY'",[visitId])).rows[0].count,1);
  } finally { await db.close(); }
});
