import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { _get } from "../../utils/ApiService";
import { Page, Field, ErrorBox, inputClass, buttonClass, londonToday, money, downloadCsv } from "../../components/Operations/common";
import ReportLibrary from "./ReportLibrary";

const unwrap = (r) => r.data.results.data;
const hours = (minutes) => (Number(minutes || 0) / 60).toFixed(1);
const pct = (value, total) => (total ? `${Math.round((Number(value) / Number(total)) * 100)}%` : "0%");
const londonTime = (value) => value ? new Intl.DateTimeFormat("en-GB", { timeZone: "Europe/London", dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not recorded";
const timingIssues = (row) => [row.lateCheckIn && `Check-in +${row.checkInLateMinutes}m`, row.lateCheckOut && `Check-out +${row.checkOutLateMinutes}m`, row.missingCheckIn && "No check-in", row.missingCheckOut && "No check-out"].filter(Boolean).join("; ");
const previousPeriod = (from, to) => {
    const start = new Date(`${from}T12:00:00Z`), end = new Date(`${to}T12:00:00Z`), days = Math.round((end - start) / 86400000) + 1;
    const oldEnd = new Date(start); oldEnd.setUTCDate(oldEnd.getUTCDate() - 1);
    const oldStart = new Date(oldEnd); oldStart.setUTCDate(oldStart.getUTCDate() - days + 1);
    return { fromB: oldStart.toISOString().slice(0, 10), toB: oldEnd.toISOString().slice(0, 10) };
};

export default function ReportIndex() {
    const [params] = useSearchParams();
    const [from, setFrom] = useState(() => /^\d{4}-\d{2}-\d{2}$/.test(params.get("from") || "") ? params.get("from") : londonToday().slice(0, 8) + "01"), [to, setTo] = useState(() => /^\d{4}-\d{2}-\d{2}$/.test(params.get("to") || "") ? params.get("to") : londonToday());
    const [tab, setTab] = useState("library"), [data, setData] = useState(null), [comparison, setComparison] = useState(null), [reconciliation, setReconciliation] = useState(null), [audits, setAudits] = useState(null), [graceMinutes, setGraceMinutes] = useState(5);
    const [error, setError] = useState(""), [loading, setLoading] = useState(false), [search, setSearch] = useState("");
    const load = useCallback(async () => {
        setLoading(true); setError("");
        try {
            const prior = previousPeriod(from, to);
            const [summary, compare, reconcile, audit] = await Promise.all([
                _get("/api/reports/summary", { params: { from, to } }),
                _get("/api/reports/compare", { params: { fromA: from, toA: to, ...prior } }),
                _get("/api/reports/reconciliation", { params: { from, to } }),
                _get("/api/reports/audits", { params: { from, to, graceMinutes } }),
            ]);
            setData(unwrap(summary)); setComparison(unwrap(compare)); setReconciliation(unwrap(reconcile)); setAudits(unwrap(audit));
        } catch (e) { setError(e.response?.data?.message || "Unable to load reporting data"); }
        finally { setLoading(false); }
    }, [from, to, graceMinutes]);
    useEffect(() => { load(); }, [load]);
    const completed = data?.byStatus.find((s) => s.status === "COMPLETED") || { visits: 0 };
    const total = data?.byStatus.filter((s) => s.status !== "CANCELLED").reduce((n, s) => n + s.visits, 0) || 0;
    const planned = data?.byStatus.reduce((n, s) => n + Number(s.minutes || 0), 0) || 0;
    const actual = data?.byStatus.reduce((n, s) => n + Number(s.actualMinutes || 0), 0) || 0;
    const clients = useMemo(() => (data?.clients || []).filter((x) => x.name.toLowerCase().includes(search.toLowerCase())), [data, search]);
    const tabs = [["library", "Report library"], ["overview", "Executive overview"], ["delivery", "Visit delivery"], ["late", "Late visits"], ["safeguarding", "Safeguarding"], ["medication", "Medication audit"], ["people", "People and clients"], ["finance", "Finance assurance"]];
    const exportOverview = () => data && downloadCsv(`caremonitor-report-${from}-${to}.csv`, [["Metric", "Value"], ["Visits", total], ["Completed visits", completed.visits], ["Planned hours", hours(planned)], ["Actual delivered hours", hours(actual)], ["Open quality cases", data.quality.openCases], ["Reconciliation issues", reconciliation?.issues.length || 0]]);
    return <Page title="Reporting and assurance" description="Live operational, care-delivery, workforce, finance and quality reporting from Caremonitor data. Times use Europe/London.">
        <section className="rounded-xl border bg-white p-4"><div className="flex flex-wrap items-end gap-3"><Field label="From"><input className={inputClass} type="date" value={from} onChange={(e) => setFrom(e.target.value)} /></Field><Field label="To"><input className={inputClass} type="date" value={to} onChange={(e) => setTo(e.target.value)} /></Field><Field label="Late grace (minutes)"><select className={inputClass} value={graceMinutes} onChange={(e) => setGraceMinutes(Number(e.target.value))}>{[0,5,10,15,30,60].map((n) => <option key={n} value={n}>{n}</option>)}</select></Field><button className={buttonClass} onClick={load} disabled={loading}>Refresh</button><button className={buttonClass} onClick={exportOverview} disabled={!data}>Export assurance summary</button></div><div className="mt-4 flex flex-wrap gap-2">{tabs.map(([key, label]) => <button key={key} onClick={() => setTab(key)} className={tab === key ? buttonClass : "rounded-lg border px-4 py-2 text-sm font-semibold text-slate-700"}>{label}</button>)}</div></section>
        <ErrorBox error={error} />{loading && <p>Loading verified report data…</p>}
        {tab === "library" && <ReportLibrary from={from} to={to} graceMinutes={graceMinutes} />}
        {!loading && data && !error && <>
            {tab === "overview" && <><div className="grid grid-cols-2 gap-3 lg:grid-cols-6"><Metric label="Visits" value={total} detail={`${comparison?.change.visits >= 0 ? "+" : ""}${comparison?.change.visits || 0} vs previous period`} /><Metric label="Completion" value={pct(completed.visits, total)} detail={`${completed.visits} completed`} /><Metric label="Actual hours" value={hours(actual)} detail={`${comparison?.change.actualMinutes >= 0 ? "+" : ""}${hours(comparison?.change.actualMinutes)} hours`} /><Metric label="Planned hours" value={hours(planned)} detail={`${hours(actual - planned)} variance`} /><Metric label="Quality cases" value={data.quality.openCases} detail={`${data.quality.overdueCases} overdue`} risk={data.quality.overdueCases > 0} /><Metric label="Reconciliation" value={reconciliation?.issues.length || 0} detail="items requiring review" risk={reconciliation?.issues.length > 0} /></div><div className="grid gap-5 lg:grid-cols-2"><StatusChart rows={data.byStatus} /><DailyTable rows={data.daily} /></div><section className="rounded-xl border border-cyan-100 bg-cyan-50 p-5 text-sm text-slate-700"><h2 className="font-semibold text-slate-900">Report definitions</h2><p className="mt-2">Actual hours use verified caregiver check-in and check-out timestamps. Planned hours use roster start and end times. Finance assurance checks inclusion in generated invoice and pay documents; it does not represent bank settlement.</p><p className="mt-2">Current active population: {data.people.clients} clients and {data.people.staff} staff. Generated for {from} to {to}; previous-period comparison uses an immediately preceding period of equal length.</p></section></>}
            {tab === "delivery" && <><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="Completed" value={completed.visits} detail={`${pct(completed.visits, total)} of visits`} /><Metric label="Actual hours" value={hours(actual)} detail="verified delivery" /><Metric label="Planned hours" value={hours(planned)} detail="scheduled delivery" /><Metric label="Missing actuals" value={reconciliation?.issues.filter((x) => x.kind === "MISSING_ACTUALS").length || 0} detail="completed visits" risk /></div><StatusChart rows={data.byStatus} /><DailyTable rows={data.daily} /></>}
            {tab === "late" && audits && <><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="Late check-ins" value={audits.lateVisits.lateCheckIns} detail={`Over ${graceMinutes} minutes after planned start`} risk /><Metric label="Late check-outs" value={audits.lateVisits.lateCheckOuts} detail={`Over ${graceMinutes} minutes after planned end`} risk /><Metric label="No check-in" value={audits.lateVisits.missingCheckIns} detail="Scheduled start has passed" risk /><Metric label="No check-out" value={audits.lateVisits.missingCheckOuts} detail="Visit end has passed or marked complete" risk /></div><p className="text-sm text-slate-600">Based on roster times and recorded actual check-in/check-out in Europe/London. Draft and cancelled visits are excluded. {audits.lateVisits.truncated && "This range has over 5,000 visits; choose a shorter range for a complete audit."}</p><div className="flex justify-end"><button className={buttonClass} onClick={() => downloadCsv(`late-visits-${from}-${to}.csv`, [["Date", "Client", "Carer", "Visit", "Planned start", "Check-in", "Planned end", "Check-out", "Issues"], ...audits.lateVisits.rows.map((x) => [x.date, x.clientName, x.staffName, x.title, londonTime(x.scheduledStart), londonTime(x.actualStart), londonTime(x.scheduledEnd), londonTime(x.actualEnd), timingIssues(x)])])}>Export late visits</button></div><DataTable title="Visits needing review" headers={["Date", "Client", "Carer", "Planned start", "Check-in", "Planned end", "Check-out", "Issue", "Record"]} rows={audits.lateVisits.rows.map((x) => [x.date, x.clientName, x.staffName || "Unassigned", londonTime(x.scheduledStart), londonTime(x.actualStart), londonTime(x.scheduledEnd), londonTime(x.actualEnd), timingIssues(x), <Link key={x.id} className="text-cyan-800 underline" to={`/admin/clients/${x.clientId}/visits?date=${x.date}&visit=${x.id}`}>Open visit</Link>])} empty="No late or missing attendance in this period." /></>}
            {tab === "safeguarding" && audits && <><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="Cases raised" value={audits.safeguarding.rows.length} detail="Created in selected period" /><Metric label="Open cases" value={audits.safeguarding.rows.filter((x) => x.status !== "CLOSED").length} detail="Not yet closed" risk /><Metric label="High or critical" value={audits.safeguarding.rows.filter((x) => x.status !== "CLOSED" && ["HIGH","CRITICAL"].includes(x.severity)).length} detail="Open risk" risk /><Metric label="Overdue" value={audits.safeguarding.rows.filter((x) => x.status !== "CLOSED" && x.dueAt && new Date(x.dueAt) < new Date()).length} detail="Action due date passed" risk /></div><p className="text-sm text-slate-600">Safeguarding cases recorded in Governance during this period. Open cases from earlier periods remain in the Governance workspace. {audits.safeguarding.truncated && "Choose a shorter range for a complete audit."}</p><DataTable title="Safeguarding cases" headers={["Raised", "Client", "Case", "Severity", "Status", "Owner", "Actions", "Due", "Record"]} rows={audits.safeguarding.rows.map((x) => [londonTime(x.createdAt), x.clientName || "No client", x.title, x.severity, x.status.replaceAll("_", " "), x.ownerName || "Unassigned", `${x.completedActions}/${x.actions}`, londonTime(x.dueAt), <Link key={x.id} className="text-cyan-800 underline" to="/admin/governance">Governance</Link>])} empty="No safeguarding cases were raised in this period." /></>}
            {tab === "medication" && audits && <><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="Administration records" value={audits.medication.rows.length} detail="Visit and historical records" /><Metric label="Refused / omitted / unavailable" value={audits.medication.rows.filter((x) => !["ADMINISTERED","PRN_ADMINISTERED"].includes(x.outcome)).length} detail="Recorded exceptions" risk /><Metric label="Corrections" value={audits.medication.rows.reduce((n, x) => n + Number(x.corrections || 0), 0)} detail="Visit eMAR amendments" /><Metric label="Open medication alerts" value={audits.medication.alerts.filter((x) => x.status === "OPEN").length} detail="Includes stock and completion overrides" risk /></div><p className="text-sm text-slate-600">Includes mobile visit eMAR and older client medication records. A record count is not a count of expected doses; review alerts and the client schedule for unrecorded doses. {audits.medication.truncated && "Choose a shorter range for a complete audit."}</p><DataTable title="Medication administrations" headers={["When", "Client", "Medication", "Slot", "Outcome", "Recorded by", "Source", "Corrections", "Record"]} rows={audits.medication.rows.map((x) => [londonTime(x.occurredAt), x.clientName, x.medication, x.slot, x.outcome.replaceAll("_", " "), x.actorName || "Not recorded", x.source === "VISIT" ? "Visit eMAR" : "Historical", x.corrections, <Link key={`${x.source}:${x.id}`} className="text-cyan-800 underline" to={`/admin/clients/${x.clientId}/medication`}>Medication</Link>])} empty="No medication administrations recorded in this period." /><DataTable title="Medication and completion alerts" headers={["Raised", "Client", "Alert", "Status", "Record"]} rows={audits.medication.alerts.map((x) => [londonTime(x.createdAt), x.clientName, x.title, x.status, <Link key={x.id} className="text-cyan-800 underline" to="/admin/inbox">Inbox</Link>])} empty="No medication-related alerts in this period." /></>}
            {tab === "people" && <><div className="flex justify-between gap-3"><input className={`${inputClass} max-w-md`} placeholder="Search client" value={search} onChange={(e) => setSearch(e.target.value)} /><button className={buttonClass} onClick={() => downloadCsv(`client-delivery-${from}-${to}.csv`, [["Client", "Visits", "Completed", "Planned hours", "Actual hours", "Missing actuals"], ...clients.map((x) => [x.name, x.visits, x.completed, hours(x.plannedMinutes), hours(x.actualMinutes), x.missingActuals])])}>Export clients</button></div><DataTable title="Client service delivery" headers={["Client", "Visits", "Completed", "Planned hours", "Actual hours", "Missing actuals"]} rows={clients.map((x) => [x.name, x.visits, x.completed, hours(x.plannedMinutes), hours(x.actualMinutes), x.missingActuals])} /><DataTable title="Staff workload" headers={["Staff", "Visits", "Completed", "Completed scheduled hours"]} rows={data.staff.map((x) => [x.name, x.visits, x.completed, hours(x.completedMinutes)])} /></>}
            {tab === "finance" && <><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="Completed visits" value={reconciliation?.completedVisits || 0} detail="eligible for review" /><Metric label="Fully reconciled" value={reconciliation?.balancedVisits || 0} detail={pct(reconciliation?.balancedVisits, reconciliation?.completedVisits)} /><Metric label="Not invoiced" value={reconciliation?.issues.filter((x) => x.kind === "NOT_INVOICED").length || 0} detail="completed visits" risk /><Metric label="Not in payrun" value={reconciliation?.issues.filter((x) => x.kind === "NOT_IN_PAYRUN").length || 0} detail="completed visits" risk /></div><DataTable title="Financial documents" headers={["Type", "Status", "Documents", "Total"]} rows={data.money.map((x) => [x.kind === "INVOICE" ? "Invoices" : "Staff pay", x.status, x.documents, money(x.totalPence)])} /><DataTable title="Reconciliation exceptions" headers={["Date", "Visit", "Issue"]} rows={(reconciliation?.issues || []).map((x) => [x.date, x.title, x.kind.replaceAll("_", " ")])} empty="No reconciliation exceptions for this period." /></>}
        </>}
    </Page>;
}
function Metric({ label, value, detail, risk = false }) { return <article className={`rounded-xl border bg-white p-4 ${risk && Number(value) ? "border-amber-300" : ""}`}><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></article>; }
function StatusChart({ rows }) { const max = Math.max(1, ...rows.map((x) => x.visits)); return <section className="space-y-4 rounded-xl border bg-white p-5"><h2 className="font-semibold">Visits by status</h2>{rows.map((x) => <div key={x.status}><div className="flex justify-between text-sm"><span>{x.status.replaceAll("_", " ")}</span><span>{x.visits}</span></div><div className="mt-1 h-3 rounded bg-slate-100"><div className="h-3 rounded bg-cyan-500" style={{ width: `${(x.visits / max) * 100}%` }} /></div></div>)}{!rows.length && <p className="text-sm text-slate-500">No visits in this period.</p>}</section>; }
function DailyTable({ rows }) { return <DataTable title="Daily delivery" headers={["Date", "Visits", "Completed", "Completion"]} rows={rows.map((x) => [x.date, x.visits, x.completed, pct(x.completed, x.visits)])} />; }
function DataTable({ title, headers, rows, empty = "No records for this period." }) { return <section className="overflow-auto rounded-xl border bg-white p-5"><h2 className="mb-3 font-semibold">{title}</h2><table className="w-full text-left text-sm"><thead><tr>{headers.map((h) => <th className="whitespace-nowrap p-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr className="border-t" key={`${row[0]}-${i}`}>{row.map((cell, j) => <td className="whitespace-nowrap p-3" key={j}>{cell}</td>)}</tr>)}</tbody></table>{!rows.length && <p className="p-3 text-sm text-slate-500">{empty}</p>}</section>; }
