import { draftHandover, missingInformation } from "./assistance.js";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { fail, reply } from "../http.js";

const actorName = (u) => [u.firstName, u.lastName].filter(Boolean).join(" ") || u.email;
const caseSchema = z.object({
  clientId: z.uuid().nullable().optional(), kind: z.enum(["INCIDENT","SAFEGUARDING","COMPLAINT","AUDIT_FINDING"]),
  severity: z.enum(["LOW","MEDIUM","HIGH","CRITICAL"]), title: z.string().trim().min(3).max(160),
  description: z.string().trim().min(10).max(5000), ownerId: z.uuid().nullable().optional(), dueAt: z.iso.datetime().nullable().optional()
});

export function registerGovernance({ db, auth, files, mail, config }, route) {
  const admin = (req) => auth.admin(req);
  const tenantUser = async (id, agency, requiredRole) => {
    if (!id) return null;
    const row = (await db.query("SELECT id,role FROM users WHERE id=$1 AND agency_id=$2 AND deleted_at IS NULL", [id, agency])).rows[0];
    if (!row || (requiredRole && row.role !== requiredRole)) fail(400, "Selected person is not eligible");
    return row;
  };
  route("GET", "/api/governance/assistance-prompts", async (req, res) => {
    admin(req);
    const rows = (await db.query(`SELECT id, first_name AS "firstName", last_name AS "lastName", primary_phone AS "primaryPhone" FROM users WHERE agency_id=$1 AND role='USER' AND deleted_at IS NULL ORDER BY id LIMIT 500`, [req.user.agencyId])).rows;
    return reply(res, { engine: "Local rules; no external AI", limit: 500, prompts: rows.flatMap(user => missingInformation(user).map(item => ({ ...item, clientId: user.id, clientName: [user.firstName,user.lastName].filter(Boolean).join(" ") || "Unnamed client" }))) });
  });
  route("GET", "/api/governance/overview", async (req,res) => {
    admin(req);
    const agency=req.user.agencyId;
    const [cases,policies,credentials,ai,lastRun]=await Promise.all([
      db.query(`SELECT count(*)::int total,count(*) FILTER(WHERE status<>'CLOSED')::int open,count(*) FILTER(WHERE due_at<CURRENT_TIMESTAMP AND status<>'CLOSED')::int overdue FROM node_quality_cases WHERE agency_id=$1`,[agency]),
      db.query(`SELECT count(*)::int total,count(*) FILTER(WHERE status='ACTIVE')::int active,count(*) FILTER(WHERE review_at<=CURRENT_DATE+30 AND status='ACTIVE')::int due FROM node_policy_register WHERE agency_id=$1`,[agency]),
      db.query(`SELECT count(*)::int total,count(*) FILTER(WHERE expires_at<CURRENT_DATE)::int expired,count(*) FILTER(WHERE expires_at BETWEEN CURRENT_DATE AND CURRENT_DATE+30)::int expiring FROM node_staff_credentials WHERE agency_id=$1 AND status='VALID'`,[agency]),
      db.query(`SELECT count(*)::int total,count(*) FILTER(WHERE status='PENDING')::int pending FROM node_ai_reviews WHERE agency_id=$1`,[agency]),
      db.query(`SELECT id,status,findings,created_at AS "createdAt" FROM node_data_quality_runs WHERE agency_id=$1 ORDER BY created_at DESC LIMIT 1`,[agency])
    ]);
    return reply(res,{quality:cases.rows[0],policies:policies.rows[0],credentials:credentials.rows[0],ai:ai.rows[0],lastDataQualityRun:lastRun.rows[0]||null});
  });
  route("GET", "/api/governance/cases", async(req,res)=>{admin(req);return reply(res,(await db.query(`SELECT q.*,u.first_name||' '||u.last_name AS "ownerName" FROM node_quality_cases q LEFT JOIN users u ON u.id=q.owner_id WHERE q.agency_id=$1 ORDER BY q.created_at DESC`,[req.user.agencyId])).rows)});
  route("POST", "/api/governance/cases", async(req,res)=>{admin(req);const p=caseSchema.safeParse(req.body);if(!p.success)fail(400,p.error.issues[0]?.message||"Invalid case");const b=p.data;await tenantUser(b.clientId,req.user.agencyId,"USER");const owner=await tenantUser(b.ownerId,req.user.agencyId);if(owner?.role==='USER')fail(400,"Case owner must be a staff member");const id=randomUUID();await db.query(`INSERT INTO node_quality_cases(id,agency_id,client_id,kind,severity,title,description,owner_id,due_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[id,req.user.agencyId,b.clientId||null,b.kind,b.severity,b.title,b.description,b.ownerId||null,b.dueAt||null,req.user.id]);return reply(res,{id},"Quality case recorded",201)});
  route("POST", "/api/governance/cases/:id/status", async(req,res)=>{admin(req);const p=z.object({status:z.enum(["OPEN","INVESTIGATING","ACTION_REQUIRED","CLOSED"]),reason:z.string().trim().min(5).max(1000),revision:z.number().int().positive()}).safeParse(req.body);if(!p.success)fail(400,"Enter a status, reason and current revision");const changed=await db.query(`UPDATE node_quality_cases SET status=$3,revision=revision+1,updated_at=CURRENT_TIMESTAMP,closed_at=CASE WHEN $3='CLOSED' THEN CURRENT_TIMESTAMP ELSE NULL END,closed_by=CASE WHEN $3='CLOSED' THEN $4::uuid ELSE NULL END,description=description||E'\n\nDecision: '||$5 WHERE id=$1 AND agency_id=$2 AND revision=$6 RETURNING id,revision`,[req.params.id,req.user.agencyId,p.data.status,req.user.id,p.data.reason,p.data.revision]);if(!changed.rows.length)fail(409,"Case changed or was not found");return reply(res,changed.rows[0],"Case status updated")});
  route("POST", "/api/governance/cases/:id/actions", async(req,res)=>{admin(req);const p=z.object({title:z.string().trim().min(3).max(300),ownerId:z.uuid().nullable().optional(),dueAt:z.iso.datetime().nullable().optional()}).safeParse(req.body);if(!p.success)fail(400,"Enter a valid corrective action");const q=(await db.query("SELECT id FROM node_quality_cases WHERE id=$1 AND agency_id=$2",[req.params.id,req.user.agencyId])).rows[0];if(!q)fail(404,"Quality case not found");const owner=await tenantUser(p.data.ownerId,req.user.agencyId);if(owner?.role==='USER')fail(400,"Action owner must be a staff member");const id=randomUUID();await db.query("INSERT INTO node_quality_actions(id,case_id,title,owner_id,due_at,created_by) VALUES($1,$2,$3,$4,$5,$6)",[id,q.id,p.data.title,p.data.ownerId||null,p.data.dueAt||null,req.user.id]);return reply(res,{id},"Corrective action added",201)});
  route("GET", "/api/governance/cases/:id/actions", async(req,res)=>{admin(req);const q=(await db.query("SELECT id FROM node_quality_cases WHERE id=$1 AND agency_id=$2",[req.params.id,req.user.agencyId])).rows[0];if(!q)fail(404,"Quality case not found");return reply(res,(await db.query(`SELECT a.*,u.first_name||' '||u.last_name AS "ownerName" FROM node_quality_actions a LEFT JOIN users u ON u.id=a.owner_id WHERE a.case_id=$1 ORDER BY a.created_at`,[q.id])).rows)});
  route("PUT", "/api/governance/cases/:id", async(req,res)=>{admin(req);const p=caseSchema.extend({revision:z.number().int().positive()}).safeParse(req.body);if(!p.success)fail(400,"Enter valid case details and revision");const b=p.data;await tenantUser(b.clientId,req.user.agencyId,"USER");const owner=await tenantUser(b.ownerId,req.user.agencyId);if(owner?.role==='USER')fail(400,"Case owner must be a staff member");const changed=await db.query(`UPDATE node_quality_cases SET client_id=$3,kind=$4,severity=$5,title=$6,description=$7,owner_id=$8,due_at=$9,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND agency_id=$2 AND revision=$10 RETURNING id,revision`,[req.params.id,req.user.agencyId,b.clientId||null,b.kind,b.severity,b.title,b.description,b.ownerId||null,b.dueAt||null,b.revision]);if(!changed.rows.length)fail(409,"Case changed or was not found");return reply(res,changed.rows[0],"Quality case updated")});
  route("POST", "/api/governance/actions/:id/status", async(req,res)=>{admin(req);const p=z.object({status:z.enum(["OPEN","DONE","VOID"]),evidence:z.string().trim().max(2000).optional()}).safeParse(req.body);if(!p.success)fail(400,"Enter an action status");const changed=await db.query(`UPDATE node_quality_actions a SET status=$3,evidence=$4,completed_at=CASE WHEN $3='DONE' THEN CURRENT_TIMESTAMP ELSE NULL END FROM node_quality_cases q WHERE a.id=$1 AND a.case_id=q.id AND q.agency_id=$2 RETURNING a.id,a.status`,[req.params.id,req.user.agencyId,p.data.status,p.data.evidence||null]);if(!changed.rows.length)fail(404,"Corrective action not found");return reply(res,changed.rows[0],"Corrective action updated")});
  route("POST", "/api/governance/cases/:id/escalate", async(req,res)=>{admin(req);const p=z.object({level:z.enum(["MANAGER","SAFEGUARDING_LEAD","DIRECTOR","REGULATOR"]),reason:z.string().trim().min(10).max(2000)}).safeParse(req.body);if(!p.success)fail(400,"Choose an escalation level and record the reason");const q=(await db.query("SELECT id FROM node_quality_cases WHERE id=$1 AND agency_id=$2",[req.params.id,req.user.agencyId])).rows[0];if(!q)fail(404,"Quality case not found");const id=randomUUID();await db.query("INSERT INTO node_governance_escalations(id,case_id,level,reason,escalated_by) VALUES($1,$2,$3,$4,$5)",[id,q.id,p.data.level,p.data.reason,req.user.id]);return reply(res,{id},"Escalation recorded",201)});
  route("GET", "/api/governance/policies", async(req,res)=>{admin(req);return reply(res,(await db.query(`SELECT p.*,count(a.user_id)::int AS acknowledgements FROM node_policy_register p LEFT JOIN node_policy_acknowledgements a ON a.policy_id=p.id WHERE p.agency_id=$1 GROUP BY p.id ORDER BY p.updated_at DESC`,[req.user.agencyId])).rows)});
  route("POST", "/api/governance/policies", async(req,res)=>{admin(req);const p=z.object({title:z.string().trim().min(3).max(160),version:z.string().trim().min(1).max(30),status:z.enum(["DRAFT","ACTIVE","RETIRED"]),effectiveAt:z.string().nullable().optional(),reviewAt:z.string().nullable().optional(),documentUrl:z.union([z.url(),z.literal(""),z.null()]).optional()}).safeParse(req.body);if(!p.success)fail(400,"Enter valid policy details");const id=randomUUID(),b=p.data;await db.query(`INSERT INTO node_policy_register(id,agency_id,title,version,status,effective_at,review_at,document_url,approved_by,approved_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$9)`,[id,req.user.agencyId,b.title,b.version,b.status,b.effectiveAt||null,b.reviewAt||null,b.documentUrl||null,req.user.id,b.status==='ACTIVE'?new Date():null]);return reply(res,{id},"Policy recorded",201)});
  route("PUT", "/api/governance/policies/:id", async(req,res)=>{admin(req);const p=z.object({title:z.string().trim().min(3).max(160),version:z.string().trim().min(1).max(30),status:z.enum(["DRAFT","ACTIVE","RETIRED"]),effectiveAt:z.string().nullable().optional(),reviewAt:z.string().nullable().optional(),documentUrl:z.union([z.url(),z.literal(""),z.null()]).optional()}).safeParse(req.body);if(!p.success)fail(400,"Enter valid policy details");const b=p.data;const changed=await db.query(`UPDATE node_policy_register SET title=$3,version=$4,status=$5,effective_at=$6,review_at=$7,document_url=$8,approved_by=CASE WHEN $5='ACTIVE' THEN $9::uuid ELSE approved_by END,approved_at=CASE WHEN $5='ACTIVE' THEN CURRENT_TIMESTAMP ELSE approved_at END,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND agency_id=$2 RETURNING id`,[req.params.id,req.user.agencyId,b.title,b.version,b.status,b.effectiveAt||null,b.reviewAt||null,b.documentUrl||null,req.user.id]);if(!changed.rows.length)fail(404,"Policy not found");return reply(res,changed.rows[0],"Policy updated")});
  route("POST", "/api/governance/policies/:id/acknowledge", async(req,res)=>{const policy=(await db.query("SELECT id FROM node_policy_register WHERE id=$1 AND agency_id=$2 AND status='ACTIVE'",[req.params.id,req.user.agencyId])).rows[0];if(!policy)fail(404,"Active policy not found");await db.query("INSERT INTO node_policy_acknowledgements(policy_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING",[policy.id,req.user.id]);return reply(res,{},"Policy acknowledged")});
  route("GET", "/api/governance/credentials", async(req,res)=>{admin(req);return reply(res,(await db.query(`SELECT c.*,u.first_name||' '||u.last_name AS "staffName",CASE WHEN c.expires_at<CURRENT_DATE THEN 'EXPIRED' WHEN c.expires_at<=CURRENT_DATE+30 THEN 'EXPIRING' ELSE c.status END AS "displayStatus" FROM node_staff_credentials c JOIN users u ON u.id=c.staff_id WHERE c.agency_id=$1 ORDER BY c.expires_at NULLS LAST`,[req.user.agencyId])).rows)});
  route("POST", "/api/governance/credentials", async(req,res)=>{admin(req);const p=z.object({staffId:z.uuid(),kind:z.string().trim().min(2).max(100),reference:z.string().trim().max(100).optional(),issuedAt:z.string().nullable().optional(),expiresAt:z.string().nullable().optional(),evidenceUrl:z.union([z.url(),z.literal(""),z.null()]).optional()}).safeParse(req.body);if(!p.success)fail(400,"Enter valid credential details");const staff=await tenantUser(p.data.staffId,req.user.agencyId);if(staff.role==='USER')fail(400,"Credential holder must be a staff member");const id=randomUUID(),b=p.data;await db.query(`INSERT INTO node_staff_credentials(id,agency_id,staff_id,kind,reference,issued_at,expires_at,evidence_url,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,req.user.agencyId,b.staffId,b.kind,b.reference||null,b.issuedAt||null,b.expiresAt||null,b.evidenceUrl||null,req.user.id]);return reply(res,{id},"Credential recorded",201)});
  route("PUT", "/api/governance/credentials/:id", async(req,res)=>{admin(req);const p=z.object({staffId:z.uuid(),kind:z.string().trim().min(2).max(100),reference:z.string().trim().max(100).optional(),issuedAt:z.string().nullable().optional(),expiresAt:z.string().nullable().optional(),evidenceUrl:z.union([z.url(),z.literal(""),z.null()]).optional(),status:z.enum(["VALID","SUSPENDED","REVOKED"]),revision:z.number().int().positive()}).safeParse(req.body);if(!p.success)fail(400,"Enter valid credential details");const staff=await tenantUser(p.data.staffId,req.user.agencyId);if(staff.role==='USER')fail(400,"Credential holder must be a staff member");const b=p.data,changed=await db.query(`UPDATE node_staff_credentials SET staff_id=$3,kind=$4,reference=$5,issued_at=$6,expires_at=$7,evidence_url=$8,status=$9,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND agency_id=$2 AND revision=$10 RETURNING id,revision`,[req.params.id,req.user.agencyId,b.staffId,b.kind,b.reference||null,b.issuedAt||null,b.expiresAt||null,b.evidenceUrl||null,b.status,b.revision]);if(!changed.rows.length)fail(409,"Credential changed or was not found");return reply(res,changed.rows[0],"Credential updated")});
  route("POST", "/api/governance/evidence/upload", async(req,res)=>{admin(req);const p=z.object({entityType:z.enum(["CASE","ACTION","POLICY","CREDENTIAL"]),entityId:z.uuid()}).safeParse(req.body);if(!p.success)fail(400,"Choose a valid record for this evidence");const tables={CASE:["node_quality_cases","id","agency_id"],ACTION:["node_quality_actions","id",null],POLICY:["node_policy_register","id","agency_id"],CREDENTIAL:["node_staff_credentials","id","agency_id"]},spec=tables[p.data.entityType];let exists;if(p.data.entityType==='ACTION')exists=(await db.query(`SELECT a.id FROM node_quality_actions a JOIN node_quality_cases q ON q.id=a.case_id WHERE a.id=$1 AND q.agency_id=$2`,[p.data.entityId,req.user.agencyId])).rows[0];else exists=(await db.query(`SELECT ${spec[1]} FROM ${spec[0]} WHERE ${spec[1]}=$1 AND ${spec[2]}=$2`,[p.data.entityId,req.user.agencyId])).rows[0];if(!exists)fail(404,"Governance record not found");const saved=await files.save(req.files?.find(x=>x.fieldname==='file')),id=randomUUID();await db.query(`INSERT INTO node_governance_evidence(id,agency_id,entity_type,entity_id,file_name,file_url,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,req.user.agencyId,p.data.entityType,p.data.entityId,saved.filename,saved.url,req.user.id]);return reply(res,{id,fileName:saved.filename,fileUrl:saved.url},"Evidence uploaded",201)},{multipart:true});
  route("GET", "/api/governance/evidence/:entityType/:entityId", async(req,res)=>{admin(req);const kind=String(req.params.entityType).toUpperCase();if(!["CASE","ACTION","POLICY","CREDENTIAL"].includes(kind))fail(400,"Invalid evidence type");return reply(res,(await db.query(`SELECT id,file_name AS "fileName",file_url AS "fileUrl",created_at AS "createdAt" FROM node_governance_evidence WHERE agency_id=$1 AND entity_type=$2 AND entity_id=$3 ORDER BY created_at DESC`,[req.user.agencyId,kind,req.params.entityId])).rows)});
  route("GET", "/api/governance/ai-reviews", async(req,res)=>{admin(req);return reply(res,(await db.query(`SELECT a.*,u.first_name||' '||u.last_name AS "clientName" FROM node_ai_reviews a JOIN users u ON u.id=a.client_id WHERE a.agency_id=$1 ORDER BY a.created_at DESC`,[req.user.agencyId])).rows)});
  route("POST", "/api/governance/ai-reviews/generate", async(req,res)=>{admin(req);const p=z.object({clientId:z.uuid(),kind:z.enum(["NOTE_SUMMARY","RISK_SIGNAL"])}).safeParse(req.body);if(!p.success)fail(400,"Choose a client and review type");await tenantUser(p.data.clientId,req.user.agencyId,"USER");await seedAiModel(db,req.user);const model=(await db.query(`SELECT id,model_key,version,limitations FROM node_ai_models WHERE agency_id=$1 AND model_key='rules-assisted' AND status='APPROVED' ORDER BY created_at DESC LIMIT 1`,[req.user.agencyId])).rows[0];if(!model)fail(409,"No approved assistance model is available");const rows=(await db.query(`SELECT id,kind,title,body,created_at AS "createdAt" FROM node_client_entries WHERE agency_id=$1 AND client_id=$2 AND kind IN ('NOTE','OBSERVATION','INCIDENT','CONCERN') ORDER BY created_at DESC LIMIT 20`,[req.user.agencyId,p.data.clientId])).rows;if(!rows.length)fail(409,"There are no eligible notes to review");const flagged=rows.filter(x=>/fall|missed|pain|injur|medication|wound|concern/i.test(`${x.title} ${x.body}`));const draft=draftHandover(rows);const suggestion=p.data.kind==='NOTE_SUMMARY'?draft.suggestion:`${flagged.length} of ${rows.length} recent entries contain possible attention terms. A qualified person must inspect the cited records.`;const id=randomUUID();await db.query(`INSERT INTO node_ai_reviews(id,agency_id,client_id,kind,suggestion,evidence,model_info,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[id,req.user.agencyId,p.data.clientId,p.data.kind,suggestion,JSON.stringify(p.data.kind === "NOTE_SUMMARY" ? draft.evidence : (flagged.length?flagged:rows.slice(0,5)).map(x=>({entryId:x.id,kind:x.kind,title:x.title,createdAt:x.createdAt}))),JSON.stringify({modelId:model.id,type:model.model_key,version:model.version,limitations:model.limitations}),req.user.id]);return reply(res,{id,suggestion},"Suggestion queued for human review",201)});
  route("POST", "/api/governance/ai-reviews/:id/decision", async(req,res)=>{admin(req);const p=z.object({decision:z.enum(["APPROVED","REJECTED"]),reason:z.string().trim().min(10).max(2000)}).safeParse(req.body);if(!p.success)fail(400,"Record an approval or rejection with a reason");const changed=await db.query(`UPDATE node_ai_reviews SET status=$3,reviewed_by=$4,decision_reason=$5,reviewed_at=CURRENT_TIMESTAMP WHERE id=$1 AND agency_id=$2 AND status='PENDING' RETURNING id,status`,[req.params.id,req.user.agencyId,p.data.decision,req.user.id,p.data.reason]);if(!changed.rows.length)fail(409,"Review was already decided or not found");return reply(res,changed.rows[0],"Human review recorded; no care record was changed")});
  route("GET", "/api/governance/ai-models", async(req,res)=>{admin(req);await seedAiModel(db,req.user);return reply(res,(await db.query(`SELECT m.*,count(e.id)::int evaluations,count(e.id) FILTER(WHERE e.outcome='PASS')::int AS "passedEvaluations" FROM node_ai_models m LEFT JOIN node_ai_evaluations e ON e.model_id=m.id WHERE m.agency_id=$1 GROUP BY m.id ORDER BY m.created_at DESC`,[req.user.agencyId])).rows)});
  route("POST", "/api/governance/ai-models", async(req,res)=>{admin(req);const p=z.object({modelKey:z.string().trim().min(2).max(80),version:z.string().trim().min(1).max(40),purpose:z.string().trim().min(10).max(1000),limitations:z.string().trim().min(10).max(2000),riskLevel:z.enum(["LOW","MEDIUM","HIGH"])}).safeParse(req.body);if(!p.success)fail(400,"Enter model purpose, version, risk and limitations");const id=randomUUID(),b=p.data;await db.query(`INSERT INTO node_ai_models(id,agency_id,model_key,version,purpose,limitations,risk_level,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[id,req.user.agencyId,b.modelKey,b.version,b.purpose,b.limitations,b.riskLevel,req.user.id]);return reply(res,{id},"Model registered in draft",201)});
  route("POST", "/api/governance/ai-models/:id/evaluations", async(req,res)=>{admin(req);const p=z.object({datasetName:z.string().trim().min(3).max(160),sampleSize:z.number().int().min(20).max(1000000),precision:z.number().min(0).max(1),recall:z.number().min(0).max(1),falsePositiveRate:z.number().min(0).max(1),subgroupResults:z.record(z.string(),z.unknown()),notes:z.string().trim().min(10).max(5000),outcome:z.enum(["PASS","FAIL","CONDITIONAL"])}).safeParse(req.body);if(!p.success)fail(400,"Enter a complete evaluation with a sample of at least 20");const model=(await db.query("SELECT id FROM node_ai_models WHERE id=$1 AND agency_id=$2",[req.params.id,req.user.agencyId])).rows[0];if(!model)fail(404,"AI model not found");const id=randomUUID(),b=p.data;await db.query(`INSERT INTO node_ai_evaluations(id,model_id,dataset_name,sample_size,precision,recall,false_positive_rate,subgroup_results,notes,outcome,reviewed_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[id,model.id,b.datasetName,b.sampleSize,b.precision,b.recall,b.falsePositiveRate,JSON.stringify(b.subgroupResults),b.notes,b.outcome,req.user.id]);return reply(res,{id},"Evaluation recorded",201)});
  route("POST", "/api/governance/ai-models/:id/status", async(req,res)=>{admin(req);await auth.requireRecent(req);const p=z.object({status:z.enum(["APPROVED","RETIRED"]),reason:z.string().trim().min(10).max(2000)}).safeParse(req.body);if(!p.success)fail(400,"Enter a model decision and reason");const model=(await db.query(`SELECT m.*,count(e.id) FILTER(WHERE e.outcome='PASS')::int passed FROM node_ai_models m LEFT JOIN node_ai_evaluations e ON e.model_id=m.id WHERE m.id=$1 AND m.agency_id=$2 GROUP BY m.id`,[req.params.id,req.user.agencyId])).rows[0];if(!model)fail(404,"AI model not found");if(p.data.status==='APPROVED'&&!model.passed)fail(409,"A passing evaluation is required before approval");await db.query(`UPDATE node_ai_models SET status=$3,approved_by=CASE WHEN $3='APPROVED' THEN $4::uuid ELSE approved_by END,approved_at=CASE WHEN $3='APPROVED' THEN CURRENT_TIMESTAMP ELSE approved_at END,limitations=limitations||E'\nDecision: '||$5 WHERE id=$1 AND agency_id=$2`,[model.id,req.user.agencyId,p.data.status,req.user.id,p.data.reason]);return reply(res,{},"Model governance decision recorded")});
  route("GET", "/api/governance/metrics", async(req,res)=>{admin(req);await seedMetrics(db,req.user);return reply(res,(await db.query(`SELECT metric_key AS "metricKey",label,definition,owner,active,updated_at AS "updatedAt" FROM node_metric_definitions WHERE agency_id=$1 ORDER BY metric_key`,[req.user.agencyId])).rows)});
  route("PUT", "/api/governance/metrics/:key", async(req,res)=>{admin(req);const p=z.object({label:z.string().trim().min(3).max(120),definition:z.string().trim().min(10).max(2000),owner:z.string().trim().min(2).max(120),active:z.boolean()}).safeParse(req.body);if(!p.success||!/^[a-z0-9_]{2,80}$/.test(req.params.key))fail(400,"Enter a valid metric definition");const b=p.data;await db.query(`INSERT INTO node_metric_definitions(agency_id,metric_key,label,definition,owner,active,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(agency_id,metric_key) DO UPDATE SET label=EXCLUDED.label,definition=EXCLUDED.definition,owner=EXCLUDED.owner,active=EXCLUDED.active,updated_by=EXCLUDED.updated_by,updated_at=CURRENT_TIMESTAMP`,[req.user.agencyId,req.params.key,b.label,b.definition,b.owner,b.active,req.user.id]);return reply(res,{},"Metric definition saved")});
  route("POST", "/api/governance/data-quality/run", async(req,res)=>{admin(req);const agency=req.user.agencyId;const findings=(await Promise.all([
    db.query(`SELECT count(*)::int n FROM node_roster_visits WHERE agency_id=$1 AND status='COMPLETED' AND (actual_start IS NULL OR actual_end IS NULL)`,[agency]),
    db.query(`SELECT count(*)::int n FROM node_quality_cases WHERE agency_id=$1 AND status<>'CLOSED' AND due_at<CURRENT_TIMESTAMP`,[agency]),
    db.query(`SELECT count(*)::int n FROM node_staff_credentials WHERE agency_id=$1 AND status='VALID' AND expires_at<CURRENT_DATE`,[agency])
  ])).map((r,i)=>({key:['completed_visits_missing_actuals','overdue_quality_cases','expired_staff_credentials'][i],count:r.rows[0].n,status:r.rows[0].n?'FAIL':'PASS'}));const id=randomUUID(),status=findings.some(x=>x.status==='FAIL')?'ATTENTION':'PASS';await db.query("INSERT INTO node_data_quality_runs(id,agency_id,status,findings,created_by) VALUES($1,$2,$3,$4,$5)",[id,agency,status,JSON.stringify(findings),req.user.id]);return reply(res,{id,status,findings,asOf:new Date().toISOString()},"Data-quality checks completed")});
  route("GET", "/api/governance/settings", async(req,res)=>{admin(req);await db.query(`INSERT INTO node_governance_settings(agency_id,updated_by) VALUES($1,$2) ON CONFLICT DO NOTHING`,[req.user.agencyId,req.user.id]);return reply(res,(await db.query(`SELECT critical_escalation_minutes AS "criticalEscalationMinutes",high_escalation_minutes AS "highEscalationMinutes",family_response_hours AS "familyResponseHours",regulator_template AS "regulatorTemplate",updated_at AS "updatedAt" FROM node_governance_settings WHERE agency_id=$1`,[req.user.agencyId])).rows[0])});
  route("PUT", "/api/governance/settings", async(req,res)=>{admin(req);const p=z.object({criticalEscalationMinutes:z.number().int().min(5).max(1440),highEscalationMinutes:z.number().int().min(15).max(10080),familyResponseHours:z.number().int().min(1).max(168),regulatorTemplate:z.enum(["CQC","CIW","CARE_INSPECTORATE","RQIA","GENERAL"])}).safeParse(req.body);if(!p.success)fail(400,"Enter valid escalation, response and regulator settings");const b=p.data;await db.query(`INSERT INTO node_governance_settings(agency_id,critical_escalation_minutes,high_escalation_minutes,family_response_hours,regulator_template,updated_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(agency_id) DO UPDATE SET critical_escalation_minutes=EXCLUDED.critical_escalation_minutes,high_escalation_minutes=EXCLUDED.high_escalation_minutes,family_response_hours=EXCLUDED.family_response_hours,regulator_template=EXCLUDED.regulator_template,updated_by=EXCLUDED.updated_by,updated_at=CURRENT_TIMESTAMP`,[req.user.agencyId,b.criticalEscalationMinutes,b.highEscalationMinutes,b.familyResponseHours,b.regulatorTemplate,req.user.id]);return reply(res,b,"Governance settings saved")});
  route("POST", "/api/governance/reminders/run", async(req,res)=>{admin(req);const agency=req.user.agencyId,settings=(await db.query(`SELECT * FROM node_governance_settings WHERE agency_id=$1`,[agency])).rows[0]||{critical_escalation_minutes:30,high_escalation_minutes:240};const rows=(await db.query(`SELECT q.id,q.title,q.severity,q.owner_id,u.email FROM node_quality_cases q JOIN users u ON u.id=q.owner_id WHERE q.agency_id=$1 AND q.status<>'CLOSED' AND q.owner_id IS NOT NULL AND ((q.severity='CRITICAL' AND q.created_at<CURRENT_TIMESTAMP-($2::text||' minutes')::interval) OR (q.severity='HIGH' AND q.created_at<CURRENT_TIMESTAMP-($3::text||' minutes')::interval) OR q.due_at<CURRENT_TIMESTAMP)`,[agency,settings.critical_escalation_minutes,settings.high_escalation_minutes])).rows;let queued=0;for(const row of rows){const key=`quality:${row.id}:${new Date().toISOString().slice(0,10)}`,id=randomUUID(),inserted=await db.query(`INSERT INTO node_governance_reminders(id,agency_id,reminder_key,recipient_id,subject,due_at) VALUES($1,$2,$3,$4,$5,CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING RETURNING id`,[id,agency,key,row.owner_id,`Action required: ${row.title}`]);if(inserted.rows.length){queued++;req.afterCommit.push(async()=>{try{await mail.send({to:row.email,subject:`Caremonitor quality escalation: ${row.title}`,text:`A ${row.severity.toLowerCase()} quality case requires review. Sign in to Caremonitor to view the protected details.`,actionUrl:`${config.frontendUrl}/admin/governance`,actionLabel:'Open governance workspace'});await db.query("UPDATE node_governance_reminders SET status='SENT',sent_at=CURRENT_TIMESTAMP WHERE id=$1",[id])}catch{await db.query("UPDATE node_governance_reminders SET status='FAILED' WHERE id=$1",[id])}})}}return reply(res,{queued,eligible:rows.length},"Governance reminders evaluated")});
  route("GET", "/api/governance/report-schedules", async(req,res)=>{admin(req);return reply(res,(await db.query(`SELECT id,name,report_kind AS "reportKind",cadence,recipient_emails AS "recipientEmails",active,last_run_at AS "lastRunAt",next_run_at AS "nextRunAt" FROM node_report_schedules WHERE agency_id=$1 ORDER BY created_at DESC`,[req.user.agencyId])).rows)});
  route("POST", "/api/governance/report-schedules", async(req,res)=>{admin(req);const p=z.object({name:z.string().trim().min(3).max(120),reportKind:z.enum(["GOVERNANCE","OPERATIONS","FINANCE_RECONCILIATION"]),cadence:z.enum(["WEEKLY","MONTHLY","QUARTERLY"]),recipientEmails:z.array(z.email()).min(1).max(20)}).safeParse(req.body);if(!p.success)fail(400,"Enter a report name, cadence and valid recipients");const id=randomUUID(),days={WEEKLY:7,MONTHLY:30,QUARTERLY:90}[p.data.cadence];await db.query(`INSERT INTO node_report_schedules(id,agency_id,name,report_kind,cadence,recipient_emails,next_run_at,created_by) VALUES($1,$2,$3,$4,$5,$6,CURRENT_TIMESTAMP+($7::text||' days')::interval,$8)`,[id,req.user.agencyId,p.data.name,p.data.reportKind,p.data.cadence,JSON.stringify([...new Set(p.data.recipientEmails.map(x=>x.toLowerCase()))]),days,req.user.id]);return reply(res,{id},"Report schedule saved",201)});
  route("GET", "/api/governance/release-signoffs", async(req,res)=>{admin(req);return reply(res,(await db.query(`SELECT s.id,s.persona,s.scenario,s.result,s.evidence,s.created_at AS "createdAt",u.first_name||' '||u.last_name AS "signedBy" FROM node_release_signoffs s JOIN users u ON u.id=s.signed_by WHERE s.agency_id=$1 ORDER BY s.created_at DESC`,[req.user.agencyId])).rows)});
  route("POST", "/api/governance/release-signoffs", async(req,res)=>{admin(req);const p=z.object({persona:z.enum(["CARE_MANAGER","CAREGIVER","CLIENT","FAMILY"]),scenario:z.string().trim().min(10).max(1000),result:z.enum(["PASS","FAIL","BLOCKED"]),evidence:z.string().trim().min(10).max(5000)}).safeParse(req.body);if(!p.success)fail(400,"Record the persona, scenario, result and evidence");const id=randomUUID();await db.query(`INSERT INTO node_release_signoffs(id,agency_id,persona,scenario,result,evidence,signed_by) VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,req.user.agencyId,p.data.persona,p.data.scenario,p.data.result,p.data.evidence,req.user.id]);return reply(res,{id},"Acceptance sign-off recorded",201)});
  route("GET", "/api/governance/evidence-pack", async(req,res)=>{admin(req);const agency=req.user.agencyId;const [overview,caseRows,policies,credentials,reviews,checks]=await Promise.all([db.query(`SELECT count(*)::int AS "qualityCases" FROM node_quality_cases WHERE agency_id=$1`,[agency]),db.query(`SELECT kind,severity,status,count(*)::int count FROM node_quality_cases WHERE agency_id=$1 GROUP BY kind,severity,status`,[agency]),db.query(`SELECT title,version,status,effective_at AS "effectiveAt",review_at AS "reviewAt" FROM node_policy_register WHERE agency_id=$1 ORDER BY title`,[agency]),db.query(`SELECT kind,status,expires_at AS "expiresAt" FROM node_staff_credentials WHERE agency_id=$1 ORDER BY expires_at`,[agency]),db.query(`SELECT kind,status,count(*)::int count FROM node_ai_reviews WHERE agency_id=$1 GROUP BY kind,status`,[agency]),db.query(`SELECT status,findings,created_at AS "createdAt" FROM node_data_quality_runs WHERE agency_id=$1 ORDER BY created_at DESC LIMIT 10`,[agency])]);return reply(res,{generatedAt:new Date().toISOString(),generatedBy:actorName(req.user),agencyId:agency,summary:overview.rows[0],cases:caseRows.rows,policies:policies.rows,credentials:credentials.rows,aiReviews:reviews.rows,dataQualityRuns:checks.rows,statement:'AI suggestions require human approval and do not modify clinical records.'})});
}

async function seedMetrics(db,user){
  for(const m of [
    ['visit_completion_rate','Visit completion rate','Completed visits divided by all non-cancelled visits in the selected period.','Registered manager'],
    ['actual_hours_delivered','Actual hours delivered','Elapsed time between verified check-in and check-out for completed visits with both timestamps.','Operations lead'],
    ['open_quality_cases','Open quality cases','Quality cases whose status is not Closed.','Quality lead'],
    ['credential_compliance','Credential compliance','Active staff credentials that have not passed their expiry date.','People lead']
  ]) await db.query(`INSERT INTO node_metric_definitions(agency_id,metric_key,label,definition,owner,updated_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING`,[user.agencyId,...m,user.id]);
}
async function seedAiModel(db,user){
  const existing=(await db.query(`SELECT id FROM node_ai_models WHERE agency_id=$1 AND model_key='rules-assisted' AND version='gate-d-1'`,[user.agencyId])).rows[0];
  if(existing)return;
  await db.query(`INSERT INTO node_ai_models(id,agency_id,model_key,version,purpose,limitations,risk_level,status,approved_by,approved_at,created_by) VALUES($1,$2,'rules-assisted','gate-d-1','Highlight words in recent care entries for qualified human review','Deterministic keyword matching can miss context and produce false positives. It is not a diagnosis or clinical conclusion.','LOW','APPROVED',$3,CURRENT_TIMESTAMP,$3)`,[randomUUID(),user.agencyId,user.id]);
}
